In [1]:
cd C:\Users\QP48568\NoSync\PWBExtractFlow

C:\Users\QP48568\NoSync\PWBExtractFlow

In [2]:
from pprint import pprint, pformat
import flow

#resp = flow.call_llm([{"role":"user", "content":"あなたはだれ"}])
#print(resp["content"])

https://test-openai-999.openai.azure.com/openai/deployments/gpt-5-mini/chat/completions?api-version=2025-01-01-preview
gpt-5-mini

In [3]:
#%load_ext jupyter_ai
#%ai list azure-chat-openai
%config AiMagics.default_language_model = " azure-chat-openai:gpt-4.1"
#%%ai azure-chat-openai:gpt-4.1
#あなたはだれ

In [4]:
# 出力ファイルを読み込み

import glob
import json
all_results = []
for path in glob.glob("out/*_result.json"):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
        if isinstance(data, list):
            all_results.extend(data)
        else:
            all_results.append(data)

In [5]:
#pprint(all_results, sort_dicts=False, width=100 )

In [6]:
from rich.pretty import pprint
pprint(all_results)
#pprint([d for d in all_results if d["report_no"] == "2224076"])

[
│   {
│   │   'report_no': '2215010',
│   │   'pdf_file': 'file://meias889/file/kosyou/2215/q2215010.pdf',
│   │   'extracted_at': '2026-03-19T11:21:52.904040+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': '真鍮製異物混入によるL4層ショート',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '発生内容が「ショート」であり、「約2Ωでショート」「L4層で回路上を異物がまたいでおり、この異物によりショート」と記載されているため、使用可能な良品である旨の記載はない。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '「積層セットアップ時に、真鍮製の異物が4層目の回路上に入り込んだことにより、ショート」と発生原因をメーカ工程起因として記載しており、客先側の責任（またはその疑い）とする記載はない。なお「実装時の半田により、最終的にショートに至ったものと考えられます」との記載はあるが、客先責と断定・示唆する記載ではない。',
│   │   │   │   │   'confidence': 0.85
│   │   │   │   },
│   │   │   │   'occurrence_cause': ['積層セットアップ時に真鍮製異物がL4回路へ混入'],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'ハトメ機周辺に粘着シート設置し異物監視',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「【2021年5月17日～実施】」と開始時期が明記されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'ハトメ設備周辺清掃時の注意点を指導徹底',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「今回の発生を受け、…作業者に対して指導しました。【2021年5月14日実施】」と記載があるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': '積層',
│   │   │   │   'escape_causes': ['対象外・検査不可'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '対策なし',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書「3.対策」に記載の2項目はいずれもハトメ機周辺の監視・清掃であり、流出防止（検査強化等）の対策は記載がありません。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': '電気',
│   │   │   │   'occurrence_cause_output': '積層セットアップ時に真鍮製異物がL4混入',
│   │   │   │   'corrective_actions_output': '粘着シート監視・清掃指導徹底',
│   │   │   │   'escape_countermeasures_output': '対策なし'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2215010_chat_history.json'
│   },
│   {
│   │   'report_no': '2215169',
│   │   'pdf_file': 'file://meias889/file/kosyou/2215/q2215169.pdf',
│   │   'extracted_at': '2026-03-19T11:21:52.905318+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': '単一不良案件',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書の「不具合内容」に「パタ－ン断線」と記載があり、また「３．現品の確認結果」にて「不具合箇所を確認するとパタ－ン断線していることを確認しました。」と記載されているため。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '報告書の「６．発生原因」にて「回路露光時に基板表面に異物が付着したため、該当箇所が露光されず不具合に至ったもの」とし、また「７．流出原因」にて検査で検出できずに「流出した」と記載されており、客先側の責任で発生した旨またはその疑いの記載がないため。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'occurrence_cause': ['回路露光時の基板表面への異物付着で未露光となったため'],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '回路工程作業者へ不具合写真回覧で認識徹底',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書「８．発生対策 1)」に今回不良のフィードバックとして記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'EDライン入室前に粘着ローラ清掃をルール化',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書「８．発生対策 3)」に「ルール化し…対策としました。（対策実施日：2021年6月7日より実施）」とあり、今回の不良に対する対策として記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'ED工程で異物対策の改善を実施（昨年度より）',
│   │   │   │   │   │   'new': False,
│   │   │   │   │   │   'reason': '報告書「８．発生対策 2)」に「昨年度より…改善を実施しております」とあり、今回以前からの継続対策であるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': 'パターン形成',
│   │   │   │   'escape_causes': ['対象外・検査不可'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '出荷検査員へ現品・写真確認を指示し認識徹底',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書「９．流出対策 1)」に、今回流出のフィードバックとして記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '外観検査機の検出設定を強化し流出防止',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書「９．流出対策 2)」に「検出設定を強化し流出対策」とあり、「対策実施日：2021年6月3日より実施」と具体記載があるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': 'AVI',
│   │   │   │   'occurrence_cause_output': '回路露光時の異物付着で未露光となった',
│   │   │   │   'corrective_actions_output': 'ED入室前ローラ清掃ルール化、不具合写真回覧',
│   │   │   │   'escape_countermeasures_output': '外観検査機設定強化、検査員へ現品写真確認'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2215169_chat_history.json'
│   },
│   {
│   │   'report_no': '2216105',
│   │   'pdf_file': 'file://meias889/file/kosyou/2216/q2216105.pdf',
│   │   'extracted_at': '2026-03-19T11:21:53.254843+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': 'マーキングにじみ（マーキング罫線がにじみ、パッド上に乗り上げ）',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書には「マーキング罫線がにじみ、パッド上に乗り上げておりました」と不具合状態が記載されている一方で、「そのまま使用可能」「修理や交換の必要がない」等の良品扱いの記載はありません。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '発生原因として「版と製品がずれ気味であったことにより…にじみが発生」および流出原因として「最終の出荷検査工程…全数目視検査…検出がもれてしまった」と記載されており、客先側の責任で発生した旨やその疑いの記載はありません。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'occurrence_cause': [
│   │   │   │   │   '版と製品ずれでインクがクリアランスに入り込みにじみ発生',
│   │   │   │   │   '試し刷りでずれを見逃し、そのまま印刷開始した'
│   │   │   │   ],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '試し刷りでクリアランスに掛かる場合は微調整',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「指導しました。【2021 年 6 月 4 日実施】」と今回不良を受けた指導の実施が記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'レジスト境界から50μm以上離して合わせる',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「50μm 以上になるように合わせることとします」「作業要領書を作成し…掲示」「【2021 年 6 月 4 日実施】」と新たな基準・要領書作成が記載されているため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': 'シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ)',
│   │   │   │   'escape_causes': ['見逃し'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '出荷検査工程へ通知し検査員へ周知徹底',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「クレーム発生通知書を発行し…認識させました。【2021 年 5 月 31 日実施】」と今回流出を受けた対応が記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '外形加工前にAVI検査機で検査し監視する',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「本図番については、外形加工前に AVI 検査機での検査を実施し…」と今後の実施が記載されているため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': '出荷',
│   │   │   │   'occurrence_cause_output': '版と製品ずれでインクが溜まりにじみ',
│   │   │   │   'corrective_actions_output': '試し刷り微調整・50μmマージン確保',
│   │   │   │   'escape_countermeasures_output': '検査員へ周知し外形加工前AVI検査'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2216105_chat_history.json'
│   },
│   {
│   │   'report_no': '2219198',
│   │   'pdf_file': 'file://meias889/file/kosyou/2219/q2219198.pdf',
│   │   'extracted_at': '2026-03-19T11:21:52.931989+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': 'マーキングにじみによるパッドへの乗り上げ',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '発生内容として「マーキングにじみ」、現品確認として「マーキングのにじみによるパッドへの乗り上げが発生しておりました」と記載されており、そのまま使用可能な良品である旨の記載はありません。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '原因として「版と製品に約70μm～約130μmのずれ」「新品のインクのみを使用したために、柔らかい状態で印刷し、にじみ傾向」といったマーキング印刷工程起因の記載、流出原因として「ベリファイ作業での良否判定時に誤判定」といった自社検査工程起因の記載があり、客先側の責任で発生した／その疑いがあるという記載はありません。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'occurrence_cause': [
│   │   │   │   │   '版と製品のずれ(約70～130μm)とにじみで乗り上げ',
│   │   │   │   │   'インクがパッド・レジスト間に入り版裏に溜まりにじみ',
│   │   │   │   │   '試し刷り微調整が不充分で印刷開始し乗り上げ発生',
│   │   │   │   │   '新品インクのみ使用で柔らかく、にじみ傾向となった'
│   │   │   │   ],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '微調整でレジスト境界から50μm以上確保',
│   │   │   │   │   │   'new': False,
│   │   │   │   │   │   'reason': '「報告書『F94)2102-Q-QC』にてご報告しております通り」かつ【2021年6月4日実施】と、今回不良以前に実施済みの記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '上記微調整ルールを再指導(10/1実施)',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「今回のフィードバックを受けて、再度…指導しました」【2021年10月1日実施】と、今回不良を受けた指導として記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '新品インク使用時は印圧調整でにじみ注意を指導',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「関係する作業者に対して…注意点を指導しました」【2021年10月1日実施】とあり、今回不良を受けた指導として記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '新品インク時は別作業者が試し刷り出来栄え確認',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「当面、新品インク使用時には…別の作業者による出来栄え確認」 と、今回不良を受けて追加した運用として記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'マーキング印刷版を280メッシュへ変更(次回～)',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「本図番については280メッシュ…使用することとします」【次回投入分～実施】とあり、今後適用の対策として記載があるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': 'シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ)',
│   │   │   │   'escape_causes': ['誤判定'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '出荷検査へ形状FBし誤判定流出を周知(10/1)',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「出荷検査工程に今回の形状をフィードバック…認識させました」【2021年10月1日実施】と、今回不良を受けて実施した内容のため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '虚報多いロットは乗り上げリスク高いと説明(10/4)',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「該当ロットのように…説明し、認識させました」【2021年10月4日実施】と、今回不良を受けて実施した内容のため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'ベリファイ画面で検出形状と良品画像を黒枠でペア表示',
│   │   │   │   │   │   'new': False,
│   │   │   │   │   │   'reason': '「誤判定防止のため…黒のラインで囲みました」【2021年6月29日実施】と、今回不良以前に実施済みの記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'AVI虚報100件超はロット識別し重点検査依頼書を発行',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「AVI検査にて…100件を超えるような場合は…ロットを識別し、『重点検査依頼書』を発行」 と、今後の運用として回答欄に具体策が記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '重点検査で最終目視検査もズレ・にじみを重点検査',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「最終の目視検査においても、マーキングのズレ・にじみを重点検査」 と、今後の運用として回答欄に具体策が記載されているため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': 'AVIベリファイ',
│   │   │   │   'occurrence_cause_output': '版ずれと新品インク起因のにじみで乗り上げ',
│   │   │   │   'corrective_actions_output': '微調整再指導と新品インク時のW確認、版変更',
│   │   │   │   'escape_countermeasures_output': '虚報多発時はロット識別し重点検査依頼書発行'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2219198_chat_history.json'
│   },
│   {
│   │   'report_no': '2223007',
│   │   'pdf_file': 'file://meias889/file/kosyou/2223/q2223007.pdf',
│   │   'extracted_at': '2026-03-19T11:21:53.294658+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': '半田濡れ不良（レジスト残渣付着）',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書には「発生内容：半田濡れ不良」「レジストの残渣により、半田濡れ不良が発生したものです。」と記載があり、不具合品である旨が示されています。一方で「そのまま使用可能」「修理や交換の必要がない良品」とする記載はありません。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '報告書では、発生原因として「水洗後の製品に対して、剥離液から製品を取り出す際に使用したゴム手袋を着用したまま取り扱ったため 、 水洗後の製品にレジストインクを含む汚れが付着」した可能性、流出原因として「良品と誤判定」等、社内工程・検査に起因する記載のみであり、客先側責任またはその疑いの記載はありません。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'occurrence_cause': ['レジスト再生処理の水洗後、剥離作業手袋で扱い汚れ付着'],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '剥離液出し入れ用ゴム手袋で他作業しない指導',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「【2022 年 3 月 16 日実施】」とあり、今回不良を受けて実施した対策として記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'レジスト再生処理要領書へ手袋他作業禁止を明記',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「作業要領書に…明記しました。【2022 年 3 月 23 日実施】」とあり、改定・明記を実施した対策として記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'レジスト再生処理の指導は改定済み要領書で実施',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「今後は改定済みの作業要領書を使用し…指導いたします。」とあり、今回不良を受けた再発防止の具体策として記載されているため。'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '各プロセス毎にゴム手袋を用意し区分使用',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「【2022 年 4 月 11 日～実施】」とあり、今回不良を受けて開始した対策として記載されているため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': 'ソルダーレジスト',
│   │   │   │   'escape_causes': ['誤判定'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '銅変色検出時の処置を整理し要領書で明確化・周知',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「処置方法を整理し、作業要領書にて明確にし、周知しました。【2022 年 3 月 16 日実施】」とあり、今回不良を受けて実施した対策として記載されているため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': 'AVIベリファイ',
│   │   │   │   'occurrence_cause_output': '水洗後、剥離作業手袋で扱い汚れ付着',
│   │   │   │   'corrective_actions_output': '手袋の他作業禁止を指導・要領書明記',
│   │   │   │   'escape_countermeasures_output': '銅変色検出時の処置を要領書明確化'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2223007_chat_history.json'
│   },
│   {
│   │   'report_no': '2224076',
│   │   'pdf_file': 'file://meias889/file/kosyou/2224/q2224076.pdf',
│   │   'extracted_at': '2026-03-19T11:21:53.083569+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': 'マーキング文字欠け',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書には「発生内容：マーキング文字欠け」「マーキング文字が欠けて判読できなくなっておりました」と不具合として記載があり、「そのまま使用可能で修理や交換の必要がない良品」とする記載はありません。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '報告書では「バケットで製品を運搬する際…マーキング文字の欠けが発生した可能性」「最終の出荷検査工程…検出が漏れた可能性」として自社側の発生・流出要因を記載しており、客先側の責任で発生した旨、またはその疑いの記載はありません。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'occurrence_cause': ['バケット運搬時の重ね積み・擦れで印刷文字が剥離'],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'バケット運搬時注意点を作業者全員に指導',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「【2022年4月20日実施】」と今回不良に対する対策として実施日付きで記載があるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': '梱包',
│   │   │   │   'escape_causes': ['見逃し'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '出荷検査へ形状FBし検出力向上',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '報告書に「今回の形状を出荷検査工程にフィードバックし…検出力向上を図りました。【2022年4月14日実施】」と、今回不良を受けた実施内容として記載があるため。'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': '出荷',
│   │   │   │   'occurrence_cause_output': 'バケット運搬時の重ね積み・擦れで剥離',
│   │   │   │   'corrective_actions_output': 'バケット運搬注意点を全員指導',
│   │   │   │   'escape_countermeasures_output': '出荷検査へ形状FBし検出力向上'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2224076_chat_history.json'
│   },
│   {
│   │   'report_no': '2228030',
│   │   'pdf_file': 'file://meias889/file/kosyou/2228/q2228030.pdf',
│   │   'extracted_at': '2026-03-19T11:21:53.345454+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': '不要穴（φ1.5、5穴）発生（外形ルーター加工時の下穴ドリル加工ずれ）',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書には「該当箇所に大きさφ1.5の不要な穴が開いている」「不要穴（5穴）」「外形加工のルータ－加工時に不要穴が基板に加工された不具合です」と記載されており、不要穴がある現品を良品（そのまま使用可能）とする記載はありません。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '発生原因として「外形ルーター加工工程で不要穴が加工された」「ルーター加工前の下穴ドリル加工がずれて加工された不具合」「固定テープが剥がれ…一番上の基板がガイドピンから外れ…ずれてしまいました」「作業者が…問題無いと判断してしまい…加工を再開したため」と、メーカ工程内の要因が記載されています。客先側要因や客先責の疑いを示す記載はありません。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'occurrence_cause': [
│   │   │   │   │   '集塵吸引で基板浮き、固定テープ剥がれ',
│   │   │   │   │   '基板がガイドピンから外れ位置ずれ',
│   │   │   │   │   'ずれた状態で下穴ドリル加工し穴位置がずれた',
│   │   │   │   │   '作業者が問題無いと判断し加工再開し不要穴加工'
│   │   │   │   ],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '不具合内容説明と現品回覧で作業者に認識',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「今回発生した…認識させました」と今回不良を受けた教育として記載され、対策実施日も示されているため'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '固定テープ剥がれ時の異常処置方法を明確化',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「今回発生した固定テープ剥がれ…異常処置方法を明確にし…（対策実施日：2022年8月23日実施）」と記載があるため'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'テープ剥がれ時は上長連絡を教育訓練で周知',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「今回発生した…必ず上長に連絡…教育訓練にて周知（対策実施日：2022年8月24日実施）」と記載があるため'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'occurrence_process': '外形加工',
│   │   │   │   'escape_causes': ['見逃し'],
│   │   │   │   'escape_countermeasures': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': '出荷検査員へ不具合説明し現品/写真回覧で教育',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「流出させてしまったことを認識」「教育いたしました」「（対策実施日：2022年8月22日実施）」と今回流出を受けた対策として記載されているため'
│   │   │   │   │   },
│   │   │   │   │   {
│   │   │   │   │   │   'text': '次回以降、外観検査機での検査対応品へ登録',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「次回以降は、外観検査機での検査対応品として登録し」「（対策実施日：2022年8月22日より実施）」と記載されているため'
│   │   │   │   │   }
│   │   │   │   ],
│   │   │   │   'inspection_process': '出荷',
│   │   │   │   'occurrence_cause_output': '集塵吸引でテープ剥がれ、基板ずれ下穴加工',
│   │   │   │   'corrective_actions_output': 'テープ剥がれ時の異常処置明確化と上長連絡徹底',
│   │   │   │   'escape_countermeasures_output': '出荷検査教育と外観検査機対応品へ登録'
│   │   │   }
│   │   ],
│   │   'conversation_history_file': 'out/2228030_chat_history.json'
│   },
│   {
│   │   'report_no': '2229127',
│   │   'pdf_file': 'file://meias889/file/kosyou/2229/q2229127.pdf',
│   │   'extracted_at': '2026-03-19T11:21:53.310717+00:00',
│   │   'failure_modes': [
│   │   │   {
│   │   │   │   'failure_mode': 'レジストインク付着によるレジスト剥がれ',
│   │   │   │   'good_judgement': {
│   │   │   │   │   'text': '不良品',
│   │   │   │   │   'reason': '報告書の「発生内容」に「レジストインク付着によるレジスト剥がれ」と記載があり、「現品を確認したところレジストインクが付着、レジストが厚くなり、一部が剥がれておりました。」と不具合状態が確認された旨が記載されている。一方で「そのまま使用可能」「修理や交換不要」等の良品扱いの記載はないため。',
│   │   │   │   │   'confidence': 0.9
│   │   │   │   },
│   │   │   │   'customer_responsibility': {
│   │   │   │   │   'text': '客先責なし',
│   │   │   │   │   'reason': '報告書の「2-1.発生原因」にて、工場の「静電スプレー塗布方式」でのレジスト塗布に関連し、「スプレーガン内の真鍮製のチューブ内にインクが残る」と「それが噴き出されて製品に付着」することで発生したと記載されている。また「2-2.流出原因」では「最終の出荷検査工程」にて「検出が漏れてしまった」としており、客先側起因/客先責の記載や示唆はないため。',
│   │   │   │   │   'confidence': 0.95
│   │   │   │   },
│   │   │   │   'occurrence_cause': ['スプレーガン真鍮チューブ内の残インクが噴き出し付着'],
│   │   │   │   'corrective_actions': [
│   │   │   │   │   {
│   │   │   │   │   │   'text': 'スプレーガン内真鍮チューブを取り外し清掃',
│   │   │   │   │   │   'new': True,
│   │   │   │   │   │   'reason': '「取り外して清掃を行いました。【2022 年 7 月 4 日実施】」と今回実施した旨の記載があるため。'
│   │   │   │   │   },
│   │   │   │   │   {

In [7]:
# DFに変換

import pandas as pd

def pformat(a):
    return a

df = pd.DataFrame([
    {
        'report_no': item['report_no'],
        'pdf_file': item['pdf_file'],
        'failure_mode': fm.get('failure_mode', ''),
        'good_judgement': fm.get('good_judgement', {}).get('text', ''),
        'good_judgement_conf': fm.get('good_judgement', {}).get('confidence', ''),
        'good_judgement_reason': fm.get('good_judgement', {}).get('reason', ''),
        'customer_responsibility': fm.get('customer_responsibility', {}).get('text', ''),
        'customer_responsibility_conf': fm.get('customer_responsibility', {}).get('confidence', ''),
        'customer_responsibility_reason': fm.get('customer_responsibility', {}).get('reason', ''),

        'occurrence_cause': pformat(fm.get('occurrence_cause', [])),
        'corrective_actions': pformat(fm.get('corrective_actions', [])),
        'occurrence_process': fm.get('occurrence_process', ''),

        'escape_causes': pformat(fm.get('escape_causes', [])),
        'escape_countermeasures': pformat(fm.get('escape_countermeasures', [])),
        'inspection_process': fm.get('inspection_process', ''),

        'occurrence_cause_output': fm.get('occurrence_cause_output', ""),
        'corrective_actions_output': fm.get('corrective_actions_output', ""),
        'escape_countermeasures_output': fm.get('escape_countermeasures_output', ""),    
}
    for item in all_results
    for fm in item.get('failure_modes', [])
])
df.to_excel('output.xlsx', index=False)
#df['pdf_file'] = df['pdf_file'].apply(lambda x: f'<a href="{x}" target="_blank">{x}</a>')
#display(HTML(df.to_html(escape=False)))
display(df)

,report_no,pdf_file,failure_mode,good_judgement,good_judgement_conf,good_judgement_reason,customer_responsibility,customer_responsibility_conf,customer_responsibility_reason,occurrence_cause,corrective_actions,occurrence_process,escape_causes,escape_countermeasures,inspection_process,occurrence_cause_output,corrective_actions_output,escape_countermeasures_output
0,2215010,file://meias889/file/kosyou/2215/q2215010.pdf,真鍮製異物混入によるL4層ショート,不良品,0.95,発生内容が「ショート」であり、「約2Ωでショート」「L4層で回路上を異物がまたいでおり、この...,客先責なし,0.85,「積層セットアップ時に、真鍮製の異物が4層目の回路上に入り込んだことにより、ショート」と発生...,[積層セットアップ時に真鍮製異物がL4回路へ混入],"[{'text': 'ハトメ機周辺に粘着シート設置し異物監視', 'new': True, ...",積層,[対象外・検査不可],"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",電気,積層セットアップ時に真鍮製異物がL4混入,粘着シート監視・清掃指導徹底,対策なし
1,2215169,file://meias889/file/kosyou/2215/q2215169.pdf,単一不良案件,不良品,0.95,報告書の「不具合内容」に「パタ－ン断線」と記載があり、また「３．現品の確認結果」にて「不具合...,客先責なし,0.90,報告書の「６．発生原因」にて「回路露光時に基板表面に異物が付着したため、該当箇所が露光されず...,[回路露光時の基板表面への異物付着で未露光となったため],"[{'text': '回路工程作業者へ不具合写真回覧で認識徹底', 'new': True,...",パターン形成,[対象外・検査不可],"[{'text': '出荷検査員へ現品・写真確認を指示し認識徹底', 'new': True...",AVI,回路露光時の異物付着で未露光となった,ED入室前ローラ清掃ルール化、不具合写真回覧,外観検査機設定強化、検査員へ現品写真確認
2,2216105,file://meias889/file/kosyou/2216/q2216105.pdf,マーキングにじみ（マーキング罫線がにじみ、パッド上に乗り上げ）,不良品,0.95,報告書には「マーキング罫線がにじみ、パッド上に乗り上げておりました」と不具合状態が記載されて...,客先責なし,0.95,発生原因として「版と製品がずれ気味であったことにより…にじみが発生」および流出原因として「最...,"[版と製品ずれでインクがクリアランスに入り込みにじみ発生, 試し刷りでずれを見逃し、そのまま...","[{'text': '試し刷りでクリアランスに掛かる場合は微調整', 'new': True...",シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ),[見逃し],"[{'text': '出荷検査工程へ通知し検査員へ周知徹底', 'new': True, '...",出荷,版と製品ずれでインクが溜まりにじみ,試し刷り微調整・50μmマージン確保,検査員へ周知し外形加工前AVI検査
3,2219198,file://meias889/file/kosyou/2219/q2219198.pdf,マーキングにじみによるパッドへの乗り上げ,不良品,0.95,発生内容として「マーキングにじみ」、現品確認として「マーキングのにじみによるパッドへの乗り上...,客先責なし,0.90,原因として「版と製品に約70μm～約130μmのずれ」「新品のインクのみを使用したために、柔...,"[版と製品のずれ(約70～130μm)とにじみで乗り上げ, インクがパッド・レジスト間に入り...","[{'text': '微調整でレジスト境界から50μm以上確保', 'new': False...",シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ),[誤判定],"[{'text': '出荷検査へ形状FBし誤判定流出を周知(10/1)', 'new': T...",AVIベリファイ,版ずれと新品インク起因のにじみで乗り上げ,微調整再指導と新品インク時のW確認、版変更,虚報多発時はロット識別し重点検査依頼書発行
4,2223007,file://meias889/file/kosyou/2223/q2223007.pdf,半田濡れ不良（レジスト残渣付着）,不良品,0.95,報告書には「発生内容：半田濡れ不良」「レジストの残渣により、半田濡れ不良が発生したものです。...,客先責なし,0.90,報告書では、発生原因として「水洗後の製品に対して、剥離液から製品を取り出す際に使用したゴム手...,[レジスト再生処理の水洗後、剥離作業手袋で扱い汚れ付着],"[{'text': '剥離液出し入れ用ゴム手袋で他作業しない指導', 'new': True...",ソルダーレジスト,[誤判定],"[{'text': '銅変色検出時の処置を整理し要領書で明確化・周知', 'new': Tr...",AVIベリファイ,水洗後、剥離作業手袋で扱い汚れ付着,手袋の他作業禁止を指導・要領書明記,銅変色検出時の処置を要領書明確化
5,2224076,file://meias889/file/kosyou/2224/q2224076.pdf,マーキング文字欠け,不良品,0.90,報告書には「発生内容：マーキング文字欠け」「マーキング文字が欠けて判読できなくなっておりまし...,客先責なし,0.90,報告書では「バケットで製品を運搬する際…マーキング文字の欠けが発生した可能性」「最終の出荷検...,[バケット運搬時の重ね積み・擦れで印刷文字が剥離],"[{'text': 'バケット運搬時注意点を作業者全員に指導', 'new': True, ...",梱包,[見逃し],"[{'text': '出荷検査へ形状FBし検出力向上', 'new': True, 'rea...",出荷,バケット運搬時の重ね積み・擦れで剥離,バケット運搬注意点を全員指導,出荷検査へ形状FBし検出力向上
6,2228030,file://meias889/file/kosyou/2228/q2228030.pdf,不要穴（φ1.5、5穴）発生（外形ルーター加工時の下穴ドリル加工ずれ）,不良品,0.90,報告書には「該当箇所に大きさφ1.5の不要な穴が開いている」「不要穴（5穴）」「外形加工のル...,客先責なし,0.95,発生原因として「外形ルーター加工工程で不要穴が加工された」「ルーター加工前の下穴ドリル加工が...,"[集塵吸引で基板浮き、固定テープ剥がれ, 基板がガイドピンから外れ位置ずれ, ずれた状態で下...","[{'text': '不具合内容説明と現品回覧で作業者に認識', 'new': True, ...",外形加工,[見逃し],"[{'text': '出荷検査員へ不具合説明し現品/写真回覧で教育', 'new': Tru...",出荷,集塵吸引でテープ剥がれ、基板ずれ下穴加工,テープ剥がれ時の異常処置明確化と上長連絡徹底,出荷検査教育と外観検査機対応品へ登録
7,2229127,file://meias889/file/kosyou/2229/q2229127.pdf,レジストインク付着によるレジスト剥がれ,不良品,0.90,報告書の「発生内容」に「レジストインク付着によるレジスト剥がれ」と記載があり、「現品を確認し...,客先責なし,0.95,報告書の「2-1.発生原因」にて、工場の「静電スプレー塗布方式」でのレジスト塗布に関連し、「...,[スプレーガン真鍮チューブ内の残インクが噴き出し付着],"[{'text': 'スプレーガン内真鍮チューブを取り外し清掃', 'new': True,...",ソルダーレジスト,[見逃し],"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",出荷,真鍮チューブ内残インク噴き出し付着,真鍮チューブ清掃と月1回交換運用,形状写真回覧、次回検査前確認、週次共有
8,222X093,file://meias889/file/kosyou/222X/q222X093.pdf,パッド欠損（回路形成時のエッチングによるパッド欠損）,不良品,0.95,報告書に「発生内容：パッド欠損」「ご指摘箇所でパッドの欠損が発生」「回路形成時のエッチングに...,客先責なし,0.90,報告書では発生原因を「外層現像ラインにて異物が付着すると…エッチングされるため今回のような欠...,[外層現像ラインで異物付着しめっき析出阻害→エッチングで欠損],"[{'text': '外層現像前コンベアー速度調整・点検実施', 'new': True, ...",パターン形成,[見逃し],"[{'text': '中間検査工程へクレーム発生通知書発行', 'new': True, '...",パターン目視,外層現像ライン異物付着で欠損,外層現像前コンベアー速度調整・点検,中間検査で履歴確認＋AOI適用
9,222X122,file://meias889/file/kosyou/222X/q222X122.pdf,レジストずれ,不良品,0.95,報告書には「発生内容：レジストずれ」「ご指摘のパッド上にレジストがずれて乗り上げておりました...,客先責なし,0.95,報告書の「2.原因」「2-1.発生原因」では、レジスト露光作業時のフィルム固定不具合（ピンと...,[レジスト露光時、フィルム固定ピンとテープが外れた状態で露光],"[{'text': 'ガイドピン外れ防止でテープ位置変更', 'new': True, 'r...",ソルダーレジスト,[誤判定],"[{'text': 'S面ずれ確認をランド→パッドへ変更し標準書改訂', 'new': Tr...",最終外観目視,露光時にピン・テープ外れでずれ,ピン外れ防止でテープ位置変更,ずれ確認をパッドで実施し標準書改訂
10,222X211,file://meias889/file/kosyou/222X/q222X211.pdf,きり穴銅箔残り,不良品,0.90,報告書には「発生内容：きり穴銅箔残り」「φ1.5 ㎜のきり穴内に銅箔残りが発生しておりました...,客先責なし,0.85,報告書では発生原因を「物理的な力によりきり穴上のドライフイルムが破れた場合に発生」「現像ライ...,[現像ラインの接触で穴上ドライフィルム破れ],"[{'text': '外層現像ラインを再度設備点検実施', 'new': True, 're...",パターン形成,[見逃し],"[{'text': '中間検査・出荷検査へクレーム発生通知書発行', 'new': True...",出荷,現像ライン接触で穴上DF破れ,外層現像ライン設備を再点検,クレーム通知・履歴書確認で検出力向上
11,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,パタ－ンずれ（回路露光用フィルムズレ）によるパッド上レジスト被さり,不良品,0.95,「パタ－ンずれにより、パット上にレジストが被さっていることを確認しました」および「パタ－ンズ...,客先責なし,0.95,発生原因として「回路露光用のフィルムがズレたこと」「回路露光機に基板をセットする時に…テープ...,[回路露光機セット時の片手持ちでテープ剥離し、露光用フィルムがズレた],"[{'text': '回路工程作業者へ不具合現品・写真を回覧し認識徹底', 'new': T...",パターン形成,[見逃し],"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",AVIベリファイ,露光機セット時片手持ちでテープ剥離し、フィルムズレ発生,露光機セット時は基板両端を持つよう教育徹底,パッド部は10倍ミニマスタ－確認をルール化
12,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,出荷検査（外観検査機ベリファイ）での誤判定／見落としによる流出,不良品,0.85,本報告書では「パタ－ンズレにより該当箇所のQFPパッド部にレジストが被さってしまい、不具合に...,客先責なし,0.95,流出原因として「外観検査機でcheckマ－クとして検出していましたが…見えていなかった」「問...,[不明],"[{'text': '対策なし', 'new': True, 'reason': '本モード...",最終外観検査,[誤判定],"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",AVIベリファイ,不明,対策なし,パッド部は10倍ミニマスタ－確認をルール化
13,222Z007,file://meias889/file/kosyou/222Z/q222Z007.pdf,内層ショート（銅片による回路間ショート）,不良品,0.95,報告書には「ご指摘箇所で 1.2Ωでショートしておりました」「発生内容：内層ショート」と記載...,客先責なし,0.90,報告書の「2-1.発生原因」にて「中間検査工程にてショートの修正を実施した際に発生した銅片が...,[中間検査のショート修正で発生した銅片が回路間に残留],"[{'text': '青テープを修正箇所1か所毎に交換し銅片除去', 'new': True...",修正,[対象外・検査不可],"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",電気,中間検査のショート修正で銅片残留,青テープを修正1か所毎に交換し銅片除去,対策なし
14,222Z028,file://meias889/file/kosyou/222Z/q222Z028.pdf,パタ－ン断線,不良品,0.95,「不具合内容：パタ－ン断線」「該当箇所のパタ－ンが導通していないことを確認しました」と記載が...,客先責なし,0.90,発生原因として「パタ－ン形成後～レジスト塗布前での当てキズ」「レジスト前処理機に基板を…セッ...,[レジスト前処理機投入時、突起接触で当てキズ発生],"[{'text': '投入機突起箇所にクッション取付', 'new': True, 'rea...",ソルダーレジスト,[対象外・検査不可],"[{'text': '外観検査機で検出不可能なため、発生対策で再発防止', 'new': T...",AVI,レジスト投入機突起接触で当てキズ,投入機突起へクッション取付・教育,検出不可のため発生対策で再発防止
15,222Z184,file://meias889/file/kosyou/222Z/q222Z184.pdf,出荷検査完了以降の取り扱い接触によるパッド曲がり（パッド斜めずれ）,不良品,0.90,「ご返却頂きました現品を確認したところ、パッドが斜めにずれていることを確認しました」および「...,客先責の疑い有,0.75,発生原因として「出荷検査工程の外観検査機による検査完了以降の製品取り扱いでの接触要因により ...,[外観検査後、専用コンテナ投入時に基板角が他基板表面へ接触し擦れ発生],"[{'text': '専用コンテナへは25シート以内で基板をしっかり持ち、角の接触を防止',...",梱包,[出荷],[{'text': '専用コンテナ内の空きスペースにクッション材をセットし基板のズレを防止'...,出荷,コンテナ投入時に基板角が接触し擦れ,25シート以内で保持し接触防止(客先責の疑い有),空きスペースへクッション材設置(客先責の疑い有)
16,2232028,file://meias889/file/kosyou/2232/q2232028.pdf,パッドへのレジストインク付着,不良品,0.90,報告書には「ご返却頂いた現品を確認したところ、いずれもパッドにレジストインクが付着しておりま...,客先責なし,0.95,報告書では「当工場では静電スプレー塗布方式でレジストインクを塗布して」おり、スプレーガン内の...,[スプレーガン内のチューブ・ノズル先にインク残り噴き出し付着],"[{'text': 'スプレーガン内の真鍮製チューブを取外し清掃', 'new': Fals...",ソルダーレジスト,[見逃し],"[{'text': '検査員へ形状写真回覧しパッド上不具合重点検査', 'new': Fal...",AVI,ガン内残インクが噴き出し付着,真鍮チューブ清掃・月1交換(継続),形状回覧し重点検査、検査員分離(継続)
17,2232052,file://meias889/file/kosyou/2232/q2232052.pdf,外層ショート（IC48ピン－IC49ピン パッド間ショート）,不良品,0.95,「発生内容：外層ショート」および「IC48 ピンと IC49 ピンのパッド間でショートしてお...,客先責なし,0.90,原因として「ドライフィルムとラミネート前に異物付着し、フィルムが浮き上がり、めっき液が潜り込...,[ドライフィルムへ異物付着し浮き、めっき液潜り込みショート],"[{'text': '端面切断をルータービット工法に統一', 'new': False, '...",パターン形成,[誤判定],"[{'text': '中間検査へフィードバックし目視注意点を指導', 'new': True...",AVIベリファイ,ドライフィルム異物付着で浮き、めっき液潜り込みショート,クリーンローラー粘着シート交換を2回/日に,ベリファイ手順見直し・全員周知で見落とし防止
18,2232121,file://meias889/file/kosyou/2232/q2232121.pdf,レジストインク付着（パッド上）,不良品,0.90,報告書には「発生内容：レジストインク付着」、また「パッドにレジストインクが付着し、部品が浮き...,客先責なし,0.90,報告書では「当工場では静電スプレー塗布方式でレジストインクを塗布」し、スプレーガン内に残った...,[スプレーガン内のインク残留が噴き出し付着],"[{'text': 'スプレーガン印加電圧を下げ付着軽減', 'new': True, 'r...",ソルダーレジスト,[見逃し],"[{'text': '目視検査員へ形状写真回覧し重点検査', 'new': True, 'r...",AVIベリファイ,スプレーガン内インク残留が噴出し付着,スプレーガン印加電圧低下で付着軽減,目視重点化、検査員分離、時間設定
19,2233016,file://meias889/file/kosyou/2233/q2233016.pdf,レジストインク付着,不良品,0.90,報告書には「発生内容：レジストインク付着」「パッドとその周辺にレジストインクが付着しておりま...,客先責なし,0.95,報告書では、発生原因として「静電スプレー塗布方式」での作業中に「スプレーガン内のチューブ内や...,[スプレーガン内に残ったインクが溜まり噴き出して付着],"[{'text': 'スプレーガンの印加電圧を下げ付着を軽減', 'new': True, ...",ソルダーレジスト,[見逃し],"[{'text': '形状写真を回覧しパッド上不具合を重点検査', 'new': True,...",AVIベリファイ,スプレーガン内残インクが噴き出し付着,スプレーガン印加電圧を下げ付着軽減,パッド上不具合を重点に目視検査強化
20,2233083,file://meias889/file/kosyou/2233/q2233083.pdf,異物付着（塗装された木片の付着）,不良品,0.85,報告書では発生内容を「異物付着」とし、「茶色い異物が付着しており、その上にシルクが印刷されて...,客先責なし,0.90,報告書の発生原因は「該当箇所に塗装された木片がシルク印刷前に付着し、残ったもの」としており、...,"[シルク印刷前に塗装された木片が基板へ付着し残留, 梱包作業台の化粧合板側面破損で木片脱落・...","[{'text': 'レジスト現像後・シルク印刷前の基板確認を周知徹底', 'new': T...",シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ),[見逃し],"[{'text': '目視検査で異物付着検出を重点化し指導', 'new': True, '...",AVI,梱包作業台破損で木片脱落し付着,梱包作業台に金属カバー取付・周知,目視検査で異物付着を重点確認
21,2234007,file://meias889/file/kosyou/2234/q2234007.pdf,レジストインク付着,不良品,0.85,報告書の発生内容として「レジストインク付着」、現品確認として「パッドとその周辺にレジストイン...,客先責なし,0.90,報告書では発生原因を「スプレーガン内のチューブ内やノズルの先にインクが残る」ことによる製品へ...,[スプレーガン内チューブ・ノズル先に残ったインクが噴き出し付着],"[{'text': '2・3ガン目の印加電圧を下げ電位差を作りミストをアース板へ誘導', '...",ソルダーレジスト,[見逃し],"[{'text': '目視検査全員に形状写真回覧しパッド上不具合検出を重点指導', 'new...",最終外観目視,ガン内残留インクが噴出し付着,2・3ガン目電圧下げミスト誘導(継続),形状写真回覧しパッド不具合重点検査
22,2234008,file://meias889/file/kosyou/2234/q2234008.pdf,単一不良案件,不良品,0.95,報告書には「異物の付着によるパタ－ンショ－ト」「不具合に至ったものと考えます」と記載があり、...,客先責なし,0.90,発生原因として「銅めっき完了後…完全に銅を除去出来ずに残ったもの」「レジスト工程で…端面から...,"[端面研磨で外周銅の除去不十分により銅残り発生, レジスト塗布時に端面銅が脱落し銅屑が付着]","[{'text': '端面研磨機に注意事項掲示し銅残り防止', 'new': True, '...",ソルダーレジスト,[対象外・検査不可],"[{'text': '流出対策は発生対策で防止する', 'new': True, 'reas...",AVI,端面研磨不良で銅残り→銅屑が付着,端面銅残り厳禁掲示と25パネル毎確認,検出困難なため発生対策で流出防止
23,2234164,file://meias889/file/kosyou/2234/q2234164.pdf,毛髪異物付着（マーキング印刷後〜乾燥前の落下）／AVIベリファイで見落とし流出,不良品,0.80,報告書の「1-1.発生状況」にて発生内容が「異物付着」とされ、「1-2.現品の確認」にて「ベ...,客先責なし,0.90,「2-1.発生原因」にて「マーキング印刷後から、乾燥前に作業者から毛髪が落下し、この箇所に付...,[マーキング印刷後～乾燥前に作業者毛髪が落下し付着],"[{'text': '印刷作業時の服装を再指導（帽子耳まで）', 'new': True, ...",シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ),[見逃し],"[{'text': '目視検査全員へ現品回覧し指導', 'new': True, 'reas...",AVIベリファイ,印刷後～乾燥前に毛髪落下し付着,印刷作業時の帽子着用を再指導・表示,ベリファイ全体確認・要領書追加等
24,2236115,file://meias889/file/kosyou/2236/q2236115.pdf,外層パターン断線（異物付着によるめっき析出阻害→欠損・断線／中間検査見逃し・通電検査で検出不可）,不良品,0.95,報告書に「C 面側のご指摘箇所で外層パターンが断線しておりました」「欠損・断線形状」とあり、...,客先責なし,0.90,発生原因を「外層露光後～パターンめっき前にて異物が付着」したことによるめっき析出阻害とし、流...,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],"[{'text': '外層現像ライン設備を再点検', 'new': True, 'reaso...",パターン形成,[見逃し],"[{'text': '中間検査工程へ形状フィードバックし流出認識', 'new': True...",パターン目視,外層露光後～パターンめっき前の異物付着,外層現像ライン再点検と水洗フィルター確認,中間検査へ形状FBし流出認識徹底
25,2236116,file://meias889/file/kosyou/2236/q2236116.pdf,外層パターン断線,不良品,0.95,報告書には「S 面側のご指摘箇所で外層パターンが断線しておりました」「擬似断線形状でした」と...,客先責なし,0.90,報告書では「外層露光後～パターンめっき前にて異物が付着」したことを発生原因としており、客先側...,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],"[{'text': '外層現像ラインのコンベアを点検', 'new': True, 'rea...",パターン形成,[見逃し],"[{'text': '中間検査工程へ形状フィードバック実施', 'new': True, '...",パターン目視,外層露光後～パターンめっき前の異物付着,外層現像ライン点検、フィルター交換後確認,中間検査へ形状フィードバック実施
26,2236121,file://meias889/file/kosyou/2236/q2236121.pdf,銅屑付着によるショ－ト,不良品,0.95,報告書には不具合内容として「パタ－ンショ－ト」および「銅屑付着によるショ－ト」と記載され、断...,客先責なし,0.90,報告書の「６．発生原因」にて、パネル外周部の銅残り→端面から脱落した銅屑が基板表面に付着した...,[端面研磨で外周銅が残り、レジスト工程で銅屑が脱落付着],"[{'text': '端面研磨機に注意喚起掲示し銅残り防止', 'new': True, '...",ソルダーレジスト,[見逃し],"[{'text': '不具合現品回覧し見落としを情報展開', 'new': True, 'r...",AVIベリファイ,端面研磨で外周銅が残り、銅屑が脱落付着,端面銅残り厳禁掲示と25パネル毎確認,ベリファイ教育と中断時の完了周知・要領書追記
27,2236199,file://meias889/file/kosyou/2236/q2236199.pdf,レジスト不良(修正痕)（レジスト異物を削り取り、レジストインクを筆で塗布した修正品の出来栄え不良）,不良品,0.85,報告書には「良品」または「そのまま使用可能で修理や交換の必要がない」との記載はありません。一...,客先責なし,0.95,報告書では「ご指摘箇所は、弊社で修正したものでした」「異物をカッターで削り取り、レジストイン...,[該当箇所のレジスト異物をカッターで削り取りした],"[{'text': 'レジストインクを均一に塗布するよう修正時注意事項を再指導', 'new...",修正,[不明],"[{'text': '今回の形状を出荷検査工程にフィードバック', 'new': True,...",出荷,レジスト異物をカッターで削り取り,修正時、レジストインクを均一塗布へ再指導,今回の形状を出荷検査工程へフィードバック
28,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,レジストインク付着（静電スプレー塗布由来）,不良品,0.92,報告書の「1-1.発生状況」にて発生内容を「レジストインク付着」とし、「1-2.現品の確認」...,客先責なし,0.95,「2-1.発生原因」にて当工場の「静電スプレー塗布方式」で、スプレーガン内のチューブやノズル...,[静電スプレー塗布中、ガン内チューブ・ノズル残インクが噴出し付着],"[{'text': '2・3ガン目の印加電圧を下げ、余剰ミストをアース板へ誘導', 'new...",ソルダーレジスト,[誤判定],"[{'text': 'ベリファイ見落とし防止要領書で、左上から順に検査を指導', 'new'...",AVIベリファイ,ガン内残インクが噴出し付着,2・3ガン目印加電圧低下でミスト低減(継続),左上から順にベリファイ指導、感度設定変更
29,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,AVI検査ベリファイ誤判定による流出,不良品,0.92,報告書の「1-1.発生状況」にて発生内容を「レジストインク付着」とし、「1-2.現品の確認」...,客先責なし,0.96,「2-2.流出原因」にて「AVI検査機が検出した形状に対して、ベリファイステーションで良否判...,[本報告書には記載がありません],"[{'text': '対策なし', 'new': True, 'reason': '本故障モ...",その他,[誤判定],"[{'text': '左上から順に検査するよう指導', 'new': True, 'reas...",AVIベリファイ,本報告書には記載がありません,対策なし,左上から順に検査指導、感度設定変更
30,2237034,file://meias889/file/kosyou/2237/q2237034.pdf,銅箔残り(金型先穴部),不良品,0.90,報告書の「発生内容」に「銅箔残り(金型先穴部)」と記載があり、現品確認でも「ご指摘箇所で銅箔...,客先責なし,0.85,「2.原因」にて現像ライン中のコンベアー接触等によりドライフィルムが破れることを発生原因とし...,[現像ラインのコンベアー接触でドライフィルム破れ],"[{'text': '水洗ラインのフィルター交換後、DF片付着無を確認', 'new': F...",パターン形成,[対象外・検査不可],"[{'text': '出荷検査へ形状FBし、スリット部銅箔残り確認を徹底', 'new': ...",出荷,現像ライン接触でDF破れ銅箔残り,対策なし(継続),出荷検査へ形状FB・要領書追記
31,2237176,file://meias889/file/kosyou/2237/q2237176.pdf,レジストずれ,不良品,0.95,報告書の発生内容として「レジストずれ」、現品確認として「パッドにレジストがずれて乗り上げてお...,客先責なし,0.90,発生原因として「フィルムの耳部分が露光機（露光テーブル奥の有効エリア外をマスクする板）に接触...,[露光工程のフィルムセット時、耳が接触しピン・テープ外れで位置ずれ],"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",ソルダーレジスト,[誤判定],"[{'text': '出荷検査工程に形状写真を回覧', 'new': True, 'reas...",出荷,露光時、フィルム耳接触で位置ずれ,フィルム耳を10mm以下へ変更,4隅後に狭隙部追加確認、写真回覧
32,2237177,file://meias889/file/kosyou/2237/q2237177.pdf,レジストインク付着（パッド上）,不良品,0.90,報告書では「発生内容：レジストインク付着」「パッドにレジストインクが付着しておりました」と不...,客先責なし,0.95,報告書には、発生原因として「スプレーガン内のチューブ内やノズルの先にインクが残ると…噴き出さ...,[スプレーガン内チューブ・ノズルに残インク蓄積し噴き出して付着],"[{'text': '2・3ガン目の印加電圧を下げミストをアース板へ誘導', 'new': ...",ソルダーレジスト,[見逃し],"[{'text': '目視検査員へ形状写真回覧しパッド不具合検出を指導', 'new': T...",最終外観目視,スプレーガン残インク噴き出し付着,印加電圧低下でミスト付着軽減(継続),目視検査でパッド不具合検出を指導
33,2237178,file://meias889/file/kosyou/2237/q2237178.pdf,外層パターン欠損（パッド欠損）,不良品,0.95,報告書にて「外層パターンが欠損しておりました」「パッドが欠損しておりました」と不具合状態が明...,客先責なし,0.90,発生原因として「外層露光後～パターンめっき前にて異物が付着」したことにより「欠損形状となりま...,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],"[{'text': '外層現像後水洗ラインのフィルター交換後、DF片付着有無を確認', 'n...",パターン形成,[見逃し],"[{'text': '中間検査工程へ欠損形状をフィードバックし流出を認識させた', 'new...",パターン目視,外層露光後～パターンめっき前の異物付着,水洗フィルター確認、DFラミメンテ,中間検査へ欠損形状をフィードバック
34,2238138,file://meias889/file/kosyou/2238/q2238138.pdf,レジストずれ,不良品,0.90,報告書の発生内容として「レジストずれ」、現品確認として「パッドにレジストがずれて乗り上げてお...,客先責なし,0.95,報告書では、発生原因を「短手側を持って隣の露光機に…セットする際に、フィルムの耳部分が…板に...,[露光機へ基板セット時、フィルム耳が板に接触しピン/テープ外れで位置ずれ],"[{'text': '露光フィルム耳部分を10mm以下へ変更', 'new': True, ...",ソルダーレジスト,[誤判定],"[{'text': '出荷検査工程へ形状写真を回覧', 'new': True, 'reas...",最終外観目視,露光機セット時のフィルム耳接触で位置ずれ,露光フィルム耳を10mm以下へ変更,形状写真回覧・狭隙部追加確認・製品カードコメント
35,2239135,file://meias889/file/kosyou/2239/q2239135.pdf,レジストずれ,不良品,0.85,報告書の「発生内容 ：レジストずれ」、および「パッドにレジストがずれて乗り上げておりました」...,客先責なし,0.90,報告書の「3-1.発生原因」および「3-2.流出原因」にて、基板とフィルムのセット作業〜露光...,[露光機セット時にフィルム耳が板へ接触し、ピンとテープが外れて基板とフィルムがずれた],"[{'text': '露光フィルムの耳部分を10mm以下へ変更', 'new': True,...",ソルダーレジスト,[誤判定],"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",最終外観目視,露光機セットでフィルムがずれた,露光フィルムの耳を10mm以下へ変更,形状写真回覧、狭隙部も追加確認
36,223X008,file://meias889/file/kosyou/223X/q223X008.pdf,パッド短絡,不良品,0.95,報告書には「パッドが短絡していることを確認しました」「パッド間で短絡していることを確認しまし...,客先責なし,0.90,発生原因として「回路露光時に基板表面に異物が付着したため、該当箇所が正常に回路形成されず不具...,[回路露光時の基板表面への異物付着で回路形成不良],"[{'text': '回路工程責任者/作業者へ不具合写真回覧', 'new': True, ...",パターン形成,[見逃し],"[{'text': '検査員へ不具合写真/現品回覧し周知', 'new': True, 'r...",AVIベリファイ,回路露光時の異物付着で短絡発生,回路工程で不具合写真を回覧,検査員へ写真/現品回覧し再教育
37,223X055,file://meias889/file/kosyou/223X/q223X055.pdf,パッド間の短絡（回路露光時の異物付着による回路形成不良／AVIベリファイで見落とし流出）,不良品,0.98,報告書には「パッド間が短絡していることを確認しました」「パッド間に銅箔が残りが発生し、短絡し...,客先責なし,0.95,発生原因として「回路露光時に基板表面に異物が付着したため、該当箇所が正常に回路形成されず不具...,[回路露光時、基板表面の異物付着で回路形成不良],"[{'text': '回路工程へ不具合写真回覧し周知徹底', 'new': True, 'r...",パターン形成,[見逃し],"[{'text': '出荷検査員へ不具合写真と現品回覧', 'new': True, 're...",AVIベリファイ,回路露光時の異物付着で回路形成不良,回路工程へ不具合写真回覧し周知徹底,検査中断ルール教育、1シート完了徹底
38,223X185,file://meias889/file/kosyou/223X/q223X185.pdf,レジストずれ,不良品,0.80,報告書の「発生内容 ：レジストずれ」として不具合を報告し、「3.原因」および「4.対策」を記...,客先責なし,0.90,「3-1.発生原因」にて、露光工程のフィルムセット作業時に「フィルムの耳部分が…板に接触し…...,[露光工程のフィルム耳が板に接触しピン・テープ外れ、基板とフィルムがずれた],"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",パターン形成,[誤判定],"[{'text': '出荷検査工程へ形状写真回覧し認識徹底', 'new': True, '...",出荷,露光時にフィルムが板接触し外れてずれ,露光用フィルム耳を10mm以下へ変更,出荷検査へ形状写真回覧し認識徹底
39,223X215,file://meias889/file/kosyou/223X/q223X215.pdf,レジストインク付着(露光不良)によるパッド欠損,不良品,0.90,「発生内容：レジストインク付着(露光不良)」として不具合を認定し、「パッドにレジストインクが...,客先責なし,0.90,「2.原因 2-1.発生原因」にて、社内工程（レジスト塗布/露光）に起因する内容（「スプレー...,"[レジスト露光時、インク片で露光フィルム浮き上がり露光阻害, スプレーガン内にインクが溜まり...","[{'text': '2・3ガン目印加電圧を下げ電位差で余分インクをアース板へ誘導', 'n...",ソルダーレジスト,[見逃し],"[{'text': '目視検査員へ形状写真回覧し、パッド上不具合検出を重点指導', 'new...",AVIベリファイ,露光時インク片で露光阻害しレジスト残り,2・3ガン目印加電圧低下でミスト低減(継続),目視検査員へ形状写真回覧し重点検査
40,223Y180,file://meias889/file/kosyou/223Y/q223Y180.pdf,ショート(パターン変形),不良品,0.95,報告書には「発生内容：ショート(パターン変形)」と記載があり、また「実装時の半田でショートに...,客先責なし,0.90,報告書の「2-1.発生原因」にて「レジスト塗布前に該当箇所が接触したため、パターンが変形」「...,[レジスト塗布前の基板セット時、投入機凸部へ接触しパターン変形],"[{'text': '投入機突起を埋めるようボード設置し接触防止', 'new': True...",ソルダーレジスト,[対象外・検査不可],"[{'text': '出荷検査工程に形状写真を回覧し流出を認識させた', 'new': Tr...",出荷,レジスト前処理研磨投入時の接触で回路曲がり,投入機突起対策＋接触時は中間検査再検査,形状写真回覧し出荷・目視検査を重点化
41,2258070,file://meias889/file/kosyou/2258/q2258070.pdf,切削粉残り,良品,0.70,第一報の「現段階での調査・対策状況」にて「(3) また、寸法については問題無いものと判断しま...,客先責なし,0.95,原因として「ルーター外形加工時の切削粉はルータービットからの排出が悪く、スリット部に付着し、...,"[ルーター外形加工時、切削粉排出不良でスリット部に付着残留, 外形加工後の歯ブラシ除去で切削...","[{'text': 'ルータービットを切削粉の排出性が良いものに変更', 'new': Tr...",外形加工,[対象外・検査不可],"[{'text': '出荷検査工程に形状回覧し流出を認識させた', 'new': True,...",出荷,外形加工で切削粉排出不良となり残留,排出性の良いルータービットへ変更(良品判定),出荷検査で形状回覧＋次回スリット粉検査(良品判定)
42,2258088,file://meias889/file/kosyou/2258/q2258088.pdf,レジストインク付着（パッドへの付着）,不良品,0.90,報告書の「1-1.発生状況」にて発生内容が「レジストインク付着」と記載され、さらに「1-2....,客先責なし,0.95,報告書の「2.原因」では「2-1.発生原因」として自社工程（静電スプレー塗布方式のレジスト塗...,[レジスト塗布設備内にミストが付着し塊化、落下して製品へ付着],"[{'text': 'セミキュア後ロボット清掃、クリップ掴みシリンダー部にカバー設置', '...",ソルダーレジスト,[誤判定],"[{'text': '出荷検査工程に形状を回覧し、今回形状の流出を認識させた', 'new'...",AVIベリファイ,設備内付着ミストが塊化し落下、製品へ付着,ロボット清掃、カバー設置等で付着防止(継続),形状回覧と要領書でベリファイ誤判定防止
43,2258125,file://meias889/file/kosyou/2258/q2258125.pdf,単一不良案件,不良品,0.90,報告書には「レジスト異物の上にマーキングされている」「シルク下に異物が混在」「該当箇所の板厚...,客先責なし,0.90,発生原因として「レジストのスプレーラインブース内に貼ってある保護シールにインクが堆積しており...,[保護シール堆積インクが脱落・浮遊し基板へ付着],"[{'text': '上部以外の保護シール交換頻度を見直し', 'new': True, '...",ソルダーレジスト,[誤判定],"[{'text': 'シルク下異物は現品確認を検討', 'new': False, 'rea...",AVIベリファイ,保護シール堆積インクが脱落し基板付着,保護シール交換頻度見直し・交換前清掃,対策なし
44,2258135,file://meias889/file/kosyou/2258/q2258135.pdf,単一不良案件,不良品,0.90,報告書には「ご指摘箇所に白色の異物を確認しました」「パッド全体が白色異物で被覆されていました...,客先責の疑い有,0.65,流出原因として「本件の異物は外観検査で検出できるものですので この異物は外観検査後に付着した...,[不明],"[{'text': '対策なし', 'new': True, 'reason': '報告書の...",その他,[混入],"[{'text': '外観検査後～アルミ梱包まで清掃', 'new': True, 'rea...",出荷,不明,対策なし(客先責の疑い有),外観検査後～梱包間の清掃・指導(客先責の疑い有)
45,2259008,file://meias889/file/kosyou/2259/q2259008.pdf,キズ・レジスト剥がれ（外力による直線状キズ／銅露出）,不良品,0.90,返却品の半田面側に「長さ約18㎜の直線状のキズ」および「パターン上のレジストが一部剥がれて銅...,客先責の疑い有,0.85,「三和大阪工場AVIログデータを確認した結果、ご指摘箇所の不具合症状を検出していないことより...,[OSP処理以降に外力で銅表面が削れキズ・レジスト剥がれ発生],"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",その他,[不明],"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",不明,OSP処理以降の外力で銅削れ・剥がれ,対策なし(客先責の疑い有),対策なし(客先責の疑い有)
46,2259032,file://meias889/file/kosyou/2259/q2259032.pdf,IC9E 11ﾋﾟﾝ付近のシルクインク付着（シルク飛散）,良品,0.95,報告書に「パッド部にインクが付着していない事、レジスト開口部にインクの付着がない事から弊社で...,客先責なし,0.95,報告書では発生原因を「インクジェットマーキングのノズル部…仕切り板があるが劣化していた事によ...,[ノズル仕切り板の劣化でインク堆積・垂れ付着],"[{'text': '工程基準にノズル定期メンテ追加(1回/15日)', 'new': Tr...",シンボル(印刷／ｲﾝｸｼﾞｪｯﾄ),[誤判定],"[{'text': 'パッド付近インク飛散を不良化し教育', 'new': True, 'r...",AVIベリファイ,ノズル仕切り板劣化でインク堆積・垂れ付着,ノズル定期メンテ(1回/15日)追加(良品判定),パッド周辺飛散を不良化し検査員教育(良品判定)
47,2259049,file://meias889/file/kosyou/2259/q2259049.pdf,レジスト異物の上にマーキングされている,不良品,0.85,「レジストに類似した異物が付着している事を確認」し、「レジスト工程で付着した異物の上にマーキ...,客先責なし,0.90,「本不具合は、レジスト工程で付着した異物の上にマーキング印字された事により発生した」とし、発...,[スプレーラインブース保護シールのインク堆積が脱落し基板へ付着],"[{'text': '上部以外も保護シール交換頻度を見直し', 'new': True, '...",ソルダーレジスト,[対象外・検査不可],"[{'text': '受け入れ検査で検出時にKINWONGへフィードバック', 'new':...",AVI,保護シール堆積インクが脱落し付着,側面等もシール交換頻度見直し・清掃標準化,受け入れ検査で検出時に客先へFB

In [8]:
#%pip install pandas
#%pip install openpyxl

In [9]:
# 人手とマージ
df_man = pd.read_excel('manual.xlsx')
df_man["報告書番号"] = df_man["報告書番号"].astype('str')
#display(df_man.head(50))
#display(df_man.info())
#display(df.info())

df_joined = pd.merge(df, df_man, how='outer', left_on='report_no', right_on='報告書番号')
#display(df_joined.columns)

# 比較してを列追加
df_joined["発生工程比較"] = df_joined["occurrence_process"] == df_joined["発生工程"]
df_joined["検査工程比較"] = df_joined["inspection_process"] == df_joined["検査工程"]
df_joined["流出要因比較"] = df_joined["escape_causes"].apply(lambda x: x[0]) == df_joined["流出要因"]


# GEN AIで比較
compare = False
if True:
    compare = True
    
    def gen_compare(a, b, mark="."):
        prompt = f"以下の(A)と(B)の意味の類似度(0.0-1.0)を出力してください。類似度の数値だけを出力してください。\n\n(A) {a}\n(B) {b}"
        resp = flow.call_llm([{"role":"user", "content":prompt}])
        print(mark, end="")
        return resp["content"]
    #print(gen_compare("日本ではポストの色は赤", "日本のポストは赤い"))

    def go1(s):
        print("go1")
        df_joined["発生要因比較"] = df_joined.apply(lambda row: gen_compare(row["発生要因"], row["occurrence_cause_output"], s), axis=1)
    def go2(s):
        print("go2")
        df_joined["発生対策比較"] = df_joined.apply(lambda row: gen_compare(row["発生対策"], row["corrective_actions_output"], s), axis=1)
    def go3(s):
        print("go3")
        df_joined["流出対策比較"] = df_joined.apply(lambda row: gen_compare(row["流出対策"], row["escape_countermeasures_output"], s), axis=1)

    print("start go1, go2, go3")
    from concurrent.futures import ThreadPoolExecutor, as_completed
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = [executor.submit(go1, "a"), executor.submit(go2, "b"), executor.submit(go3, "c")]
    for future in as_completed(futures):
        print(future.result())

# 出力
cols = [
    "report_no", "pdf_file",
    "occurrence_cause", "occurrence_cause_output", "発生要因", "発生要因比較",
    "corrective_actions", "corrective_actions_output", "発生対策", "発生対策比較",
    "occurrence_process", "発生工程", "発生工程比較",
    "escape_causes", "流出要因", "流出要因比較", 
    "escape_countermeasures", "escape_countermeasures_output", "流出対策", "流出対策比較",
    "inspection_process", "検査工程", "検査工程比較",
    "failure_mode", "good_judgement", "customer_responsibility", 
]
#display(df_joined.columns)
display(df_joined[cols])
if comare:
    df_joined[cols].to_excel('out_joined.xlsx', index=False)
else:
    df_joined[cols].to_excel('out_joined_nocomp.xlsx', index=False)

start go1, go2, go3
go1
go2
go3
cabcabcabcbacbacbacbacbacabcbacabacbacbaccacabcacbacbababababacbacbacbacbacbacbabacabcabaccaabcbacbacbcabacbbacbbcacbacbacbabcabacbabcabccbcacbbacbcccNone
None
None

start1

start2

start3

end

,report_no,pdf_file,occurrence_cause,occurrence_cause_output,発生要因,発生要因比較,corrective_actions,corrective_actions_output,発生対策,発生対策比較,...,escape_countermeasures,escape_countermeasures_output,流出対策,流出対策比較,inspection_process,検査工程,検査工程比較,failure_mode,good_judgement,customer_responsibility
0,2215010,file://meias889/file/kosyou/2215/q2215010.pdf,[積層セットアップ時に真鍮製異物がL4回路へ混入],積層セットアップ時に真鍮製異物がL4混入,ハトメピンの破片の混入,0.7,"[{'text': 'ハトメ機周辺に粘着シート設置し異物監視', 'new': True, ...",粘着シート監視・清掃指導徹底,粘着シートを設置し、破片の発生個所の確認,0.75,...,"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",対策なし,なし,0.9,電気,電気,True,真鍮製異物混入によるL4層ショート,不良品,客先責なし
1,2215169,file://meias889/file/kosyou/2215/q2215169.pdf,[回路露光時の基板表面への異物付着で未露光となったため],回路露光時の異物付着で未露光となった,異物による露光阻害,0.95,"[{'text': '回路工程作業者へ不具合写真回覧で認識徹底', 'new': True,...",ED入室前ローラ清掃ルール化、不具合写真回覧,EDライン入室時はクリーン服を粘着ローラで清掃,0.9,...,"[{'text': '出荷検査員へ現品・写真確認を指示し認識徹底', 'new': True...",外観検査機設定強化、検査員へ現品写真確認,作業者への注意喚起,0.35,AVI,AVI,True,単一不良案件,不良品,客先責なし
2,2216105,file://meias889/file/kosyou/2216/q2216105.pdf,"[版と製品ずれでインクがクリアランスに入り込みにじみ発生, 試し刷りでずれを見逃し、そのまま...",版と製品ずれでインクが溜まりにじみ,印刷版裏へのインクにじみ,0.60,"[{'text': '試し刷りでクリアランスに掛かる場合は微調整', 'new': True...",試し刷り微調整・50μmマージン確保,版の位置の微調整を作業要領書で再規定・教育,0.6,...,"[{'text': '出荷検査工程へ通知し検査員へ周知徹底', 'new': True, '...",検査員へ周知し外形加工前AVI検査,作業者への注意喚起,0.35,出荷,AVIベリファイ【最終外観目視】,False,マーキングにじみ（マーキング罫線がにじみ、パッド上に乗り上げ）,不良品,客先責なし
3,2219198,file://meias889/file/kosyou/2219/q2219198.pdf,"[版と製品のずれ(約70～130μm)とにじみで乗り上げ, インクがパッド・レジスト間に入り...",版ずれと新品インク起因のにじみで乗り上げ,印刷版裏へのインクにじみ,0.6,"[{'text': '微調整でレジスト境界から50μm以上確保', 'new': False...",微調整再指導と新品インク時のW確認、版変更,版のメッシュ開口を微細化,0.5,...,"[{'text': '出荷検査へ形状FBし誤判定流出を周知(10/1)', 'new': T...",虚報多発時はロット識別し重点検査依頼書発行,検査画面の区分線追加による強調表示,0.15,AVIベリファイ,AVIベリファイ,True,マーキングにじみによるパッドへの乗り上げ,不良品,客先責なし
4,2223007,file://meias889/file/kosyou/2223/q2223007.pdf,[レジスト再生処理の水洗後、剥離作業手袋で扱い汚れ付着],水洗後、剥離作業手袋で扱い汚れ付着,レジスト再処理時の手袋からの転写,0.90,"[{'text': '剥離液出し入れ用ゴム手袋で他作業しない指導', 'new': True...",手袋の他作業禁止を指導・要領書明記,再処理工程の手袋の使用規定の再教育,0.75,...,"[{'text': '銅変色検出時の処置を整理し要領書で明確化・周知', 'new': Tr...",銅変色検出時の処置を要領書明確化,パッド上の変色への対応を明文化,0.95,AVIベリファイ,AVIベリファイ,True,半田濡れ不良（レジスト残渣付着）,不良品,客先責なし
5,2224076,file://meias889/file/kosyou/2224/q2224076.pdf,[バケット運搬時の重ね積み・擦れで印刷文字が剥離],バケット運搬時の重ね積み・擦れで剥離,搬送箱内での振動による基板同士の擦れ,0.85,"[{'text': 'バケット運搬時注意点を作業者全員に指導', 'new': True, ...",バケット運搬注意点を全員指導,作業者への注意喚起,0.75,...,"[{'text': '出荷検査へ形状FBし検出力向上', 'new': True, 'rea...",出荷検査へ形状FBし検出力向上,作業者への注意喚起,0.15,出荷,出荷,True,マーキング文字欠け,不良品,客先責なし
6,2228030,file://meias889/file/kosyou/2228/q2228030.pdf,"[集塵吸引で基板浮き、固定テープ剥がれ, 基板がガイドピンから外れ位置ずれ, ずれた状態で下...",集塵吸引でテープ剥がれ、基板ずれ下穴加工,ルーター加工時の固定テープの剥がれ,0.75,"[{'text': '不具合内容説明と現品回覧で作業者に認識', 'new': True, ...",テープ剥がれ時の異常処置明確化と上長連絡徹底,テープ剥がれ時の異常処置を明文化,0.85,...,"[{'text': '出荷検査員へ不具合説明し現品/写真回覧で教育', 'new': Tru...",出荷検査教育と外観検査機対応品へ登録,作業者への注意喚起,0.15,出荷,出荷,True,不要穴（φ1.5、5穴）発生（外形ルーター加工時の下穴ドリル加工ずれ）,不良品,客先責なし
7,2229127,file://meias889/file/kosyou/2229/q2229127.pdf,[スプレーガン真鍮チューブ内の残インクが噴き出し付着],真鍮チューブ内残インク噴き出し付着,スプレーガン内のインク残り,0.65,"[{'text': 'スプレーガン内真鍮チューブを取り外し清掃', 'new': True,...",真鍮チューブ清掃と月1回交換運用,スプレーガンの真鍮チューブの清掃頻度を1年/回→1月/回に変更,0.8,...,"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",形状写真回覧、次回検査前確認、週次共有,作業者への注意喚起,0.6,出荷,最終外観目視【/出荷】,False,レジストインク付着によるレジスト剥がれ,不良品,客先責なし
8,222X093,file://meias889/file/kosyou/222X/q222X093.pdf,[外層現像ラインで異物付着しめっき析出阻害→エッチングで欠損],外層現像ライン異物付着で欠損,異物による露光阻害,0.75,"[{'text': '外層現像前コンベアー速度調整・点検実施', 'new': True, ...",外層現像前コンベアー速度調整・点検,コンベア間の速度調整,0.7,...,"[{'text': '中間検査工程へクレーム発生通知書発行', 'new': True, '...",中間検査で履歴確認＋AOI適用,作業者への注意喚起,0.2,パターン目視,パターン目視,True,パッド欠損（回路形成時のエッチングによるパッド欠損）,不良品,客先責なし
9,222X122,file://meias889/file/kosyou/222X/q222X122.pdf,[レジスト露光時、フィルム固定ピンとテープが外れた状態で露光],露光時にピン・テープ外れでずれ,露光フィルムのずれ,0.9,"[{'text': 'ガイドピン外れ防止でテープ位置変更', 'new': True, 'r...",ピン外れ防止でテープ位置変更,露光フィルムの固定用のテープ貼り付け位置の変更,0.7,...,"[{'text': 'S面ずれ確認をランド→パッドへ変更し標準書改訂', 'new': Tr...",ずれ確認をパッドで実施し標準書改訂,ずれの確認箇所をランドからパッドに変更,0.9,最終外観目視,最終外観目視,True,レジストずれ,不良品,客先責なし
10,222X211,file://meias889/file/kosyou/222X/q222X211.pdf,[現像ラインの接触で穴上ドライフィルム破れ],現像ライン接触で穴上DF破れ,ドライフィルム破れ,0.90,"[{'text': '外層現像ラインを再度設備点検実施', 'new': True, 're...",外層現像ライン設備を再点検,コンベア間の速度調整,0.1,...,"[{'text': '中間検査・出荷検査へクレーム発生通知書発行', 'new': True...",クレーム通知・履歴書確認で検出力向上,作業者への注意喚起,0.15,出荷,出荷,True,きり穴銅箔残り,不良品,客先責なし
11,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,[回路露光機セット時の片手持ちでテープ剥離し、露光用フィルムがズレた],露光機セット時片手持ちでテープ剥離し、フィルムズレ発生,露光フィルムのずれ,0.9,"[{'text': '回路工程作業者へ不具合現品・写真を回覧し認識徹底', 'new': T...",露光機セット時は基板両端を持つよう教育徹底,基板の両手持ちの再教育,0.9,...,"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",パッド部は10倍ミニマスタ－確認をルール化,作業者への注意喚起,0.35,AVIベリファイ,AVIベリファイ,True,パタ－ンずれ（回路露光用フィルムズレ）によるパッド上レジスト被さり,不良品,客先責なし
12,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,[不明],不明,露光フィルムのずれ,0.0,"[{'text': '対策なし', 'new': True, 'reason': '本モード...",対策なし,基板の両手持ちの再教育,0.1,...,"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",パッド部は10倍ミニマスタ－確認をルール化,作業者への注意喚起,0.5,AVIベリファイ,AVIベリファイ,True,出荷検査（外観検査機ベリファイ）での誤判定／見落としによる流出,不良品,客先責なし
13,222Z007,file://meias889/file/kosyou/222Z/q222Z007.pdf,[中間検査のショート修正で発生した銅片が回路間に残留],中間検査のショート修正で銅片残留,パターン修正時の銅片の再付着,0.88,"[{'text': '青テープを修正箇所1か所毎に交換し銅片除去', 'new': True...",青テープを修正1か所毎に交換し銅片除去,銅片除去に使用するテープの交換頻度を10回毎→1回毎に変更,0.95,...,"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",対策なし,なし,0.85,電気,電気,True,内層ショート（銅片による回路間ショート）,不良品,客先責なし
14,222Z028,file://meias889/file/kosyou/222Z/q222Z028.pdf,[レジスト前処理機投入時、突起接触で当てキズ発生],レジスト投入機突起接触で当てキズ,ハンドリング時の傷,0.9,"[{'text': '投入機突起箇所にクッション取付', 'new': True, 'rea...",投入機突起へクッション取付・教育,投入機の角部にクッションを設置,0.75,...,"[{'text': '外観検査機で検出不可能なため、発生対策で再発防止', 'new': T...",検出不可のため発生対策で再発防止,なし,0.0,AVI,AVI,True,パタ－ン断線,不良品,客先責なし
15,222Z184,file://meias889/file/kosyou/222Z/q222Z184.pdf,[外観検査後、専用コンテナ投入時に基板角が他基板表面へ接触し擦れ発生],コンテナ投入時に基板角が接触し擦れ,ハンドリング時の傷,0.8,"[{'text': '専用コンテナへは25シート以内で基板をしっかり持ち、角の接触を防止',...",25シート以内で保持し接触防止(客先責の疑い有),作業者への注意喚起,0.15,...,[{'text': '専用コンテナ内の空きスペースにクッション材をセットし基板のズレを防止'...,空きスペースへクッション材設置(客先責の疑い有),なし,0.0,出荷,出荷,True,出荷検査完了以降の取り扱い接触によるパッド曲がり（パッド斜めずれ）,不良品,客先責の疑い有
16,2232028,file://meias889/file/kosyou/2232/q2232028.pdf,[スプレーガン内のチューブ・ノズル先にインク残り噴き出し付着],ガン内残インクが噴き出し付着,スプレーガン内のインク残り,0.9,"[{'text': 'スプレーガン内の真鍮製チューブを取外し清掃', 'new': Fals...",真鍮チューブ清掃・月1交換(継続),スプレーガンの真鍮チューブの清掃頻度を1年/回→1月/回に変更,0.92,...,"[{'text': '検査員へ形状写真回覧しパッド上不具合重点検査', 'new': Fal...",形状回覧し重点検査、検査員分離(継続),1ワーク当たりの検査時間を守れるように、検査員を分ける,0.7,AVI,最終外観目視,False,パッドへのレジストインク付着,不良品,客先責なし
17,2232052,file://meias889/file/kosyou/2232/q2232052.pdf,[ドライフィルムへ異物付着し浮き、めっき液潜り込みショート],ドライフィルム異物付着で浮き、めっき液潜り込みショート,異物によるめっきレジスト形成阻害,0.88,"[{'text': '端面切断をルータービット工法に統一', 'new': False, '...",クリーンローラー粘着シート交換を2回/日に,なし,0.0,...,"[{'text': '中間検査へフィードバックし目視注意点を指導', 'new': True...",ベリファイ手順見直し・全員周知で見落とし防止,作業者への注意喚起,0.6,AVIベリファイ,AVIベリファイ,True,外層ショート（IC48ピン－IC49ピン パッド間ショート）,不良品,客先責なし
18,2232121,file://meias889/file/kosyou/2232/q2232121.pdf,[スプレーガン内のインク残留が噴き出し付着],スプレーガン内インク残留が噴出し付着,スプレーガン内のインク残り,0.80,"[{'text': 'スプレーガン印加電圧を下げ付着軽減', 'new': True, 'r...",スプレーガン印加電圧低下で付着軽減,レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': '目視検査員へ形状写真回覧し重点検査', 'new': True, 'r...",目視重点化、検査員分離、時間設定,製品仕様毎に標準検査時間を設定,0.8,AVIベリファイ,最終外観目視,False,レジストインク付着（パッド上）,不良品,客先責なし
19,2233016,file://meias889/file/kosyou/2233/q2233016.pdf,[スプレーガン内に残ったインクが溜まり噴き出して付着],スプレーガン内残インクが噴き出し付着,スプレーガン内のインク残り,0.85,"[{'text': 'スプレーガンの印加電圧を下げ付着を軽減', 'new': True, ...",スプレーガン印加電圧を下げ付着軽減,レジスト塗布時の印加電圧を変更,0.85,...,"[{'text': '形状写真を回覧しパッド上不具合を重点検査', 'new': True,...",パッド上不具合を重点に目視検査強化,製品仕様毎に標準検査時間を設定,0.35,AVIベリファイ,最終外観目視,False,レジストインク付着,不良品,客先責なし
20,2233083,file://meias889/file/kosyou/2233/q2233083.pdf,"[シルク印刷前に塗装された木片が基板へ付着し残留, 梱包作業台の化粧合板側面破損で木片脱落・...",梱包作業台破損で木片脱落し付着,印刷時の異物混入,0.6,"[{'text': 'レジスト現像後・シルク印刷前の基板確認を周知徹底', 'new': T...",梱包作業台に金属カバー取付・周知,なし,0.0,...,"[{'text': '目視検査で異物付着検出を重点化し指導', 'new': True, '...",目視検査で異物付着を重点確認,作業者への注意喚起,0.30,AVI,最終外観目視,False,異物付着（塗装された木片の付着）,不良品,客先責なし
21,2234007,file://meias889/file/kosyou/2234/q2234007.pdf,[スプレーガン内チューブ・ノズル先に残ったインクが噴き出し付着],ガン内残留インクが噴出し付着,スプレーガン内のインク残り,0.8,"[{'text': '2・3ガン目の印加電圧を下げ電位差を作りミストをアース板へ誘導', '...",2・3ガン目電圧下げミスト誘導(継続),レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': '目視検査全員に形状写真回覧しパッド上不具合検出を重点指導', 'new...",形状写真回覧しパッド不具合重点検査,製品仕様毎に標準検査時間を設定,0.25,最終外観目視,最終外観目視,True,レジストインク付着,不良品,客先責なし
22,2234008,file://meias889/file/kosyou/2234/q2234008.pdf,"[端面研磨で外周銅の除去不十分により銅残り発生, レジスト塗布時に端面銅が脱落し銅屑が付着]",端面研磨不良で銅残り→銅屑が付着,端面研磨不足による端部への銅残り,0.95,"[{'text': '端面研磨機に注意事項掲示し銅残り防止', 'new': True, '...",端面銅残り厳禁掲示と25パネル毎確認,なし,0.0,...,"[{'text': '流出対策は発生対策で防止する', 'new': True, 'reas...",検出困難なため発生対策で流出防止,端面研磨後、25パネル毎に銅残りないことを確認する検査を追加,0.15,AVI,その他【AVI】,False,単一不良案件,不良品,客先責なし
23,2234164,file://meias889/file/kosyou/2234/q2234164.pdf,[マーキング印刷後～乾燥前に作業者毛髪が落下し付着],印刷後～乾燥前に毛髪落下し付着,印刷後の異物混入,0.85,"[{'text': '印刷作業時の服装を再指導（帽子耳まで）', 'new': True, ...",印刷作業時の帽子着用を再指導・表示,服装規定の追加掲示,0.7,...,"[{'text': '目視検査全員へ現品回覧し指導', 'new': True, 'reas...",ベリファイ全体確認・要領書追加等,見落としやすい不良項目として、教育資料に本不良写真を追加,0.65,AVIベリファイ,AVIベリファイ,True,毛髪異物付着（マーキング印刷後〜乾燥前の落下）／AVIベリファイで見落とし流出,不良品,客先責なし
24,2236115,file://meias889/file/kosyou/2236/q2236115.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.7,"[{'text': '外層現像ライン設備を再点検', 'new': True, 'reaso...",外層現像ライン再点検と水洗フィルター確認,なし,0.0,...,"[{'text': '中間検査工程へ形状フィードバックし流出認識', 'new': True...",中間検査へ形状FBし流出認識徹底,作業者への注意喚起,0.45,パターン目視,パターン目視,True,外層パターン断線（異物付着によるめっき析出阻害→欠損・断線／中間検査見逃し・通電検査で検出不可）,不良品,客先責なし
25,2236116,file://meias889/file/kosyou/2236/q2236116.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.35,"[{'text': '外層現像ラインのコンベアを点検', 'new': True, 'rea...",外層現像ライン点検、フィルター交換後確認,なし,0.0,...,"[{'text': '中間検査工程へ形状フィードバック実施', 'new': True, '...",中間検査へ形状フィードバック実施,作業者への注意喚起,0.2,パターン目視,パターン目視,True,外層パターン断線,不良品,客先責なし
26,2236121,file://meias889/file/kosyou/2236/q2236121.pdf,[端面研磨で外周銅が残り、レジスト工程で銅屑が脱落付着],端面研磨で外周銅が残り、銅屑が脱落付着,端面研磨不足による端部への銅残り,0.90,"[{'text': '端面研磨機に注意喚起掲示し銅残り防止', 'new': True, '...",端面銅残り厳禁掲示と25パネル毎確認,なし,0.0,...,"[{'text': '不具合現品回覧し見落としを情報展開', 'new': True, 'r...",ベリファイ教育と中断時の完了周知・要領書追記,検査中は中断禁止を要領書に追記,0.55,AVIベリファイ,AVIベリファイ,True,銅屑付着によるショ－ト,不良品,客先責なし
27,2236199,file://meias889/file/kosyou/2236/q2236199.pdf,[該当箇所のレジスト異物をカッターで削り取りした],レジスト異物をカッターで削り取り,レジスト修正時の塗布量が少ない,0.2,"[{'text': 'レジストインクを均一に塗布するよう修正時注意事項を再指導', 'new...",修正時、レジストインクを均一塗布へ再指導,塗布見本を要領書に追記,0.6,...,"[{'text': '今回の形状を出荷検査工程にフィードバック', 'new': True,...",今回の形状を出荷検査工程へフィードバック,作業者への注意喚起,0.25,出荷,その他【出荷】,False,レジスト不良(修正痕)（レジスト異物を削り取り、レジストインクを筆で塗布した修正品の出来栄え不良）,不良品,客先責なし
28,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,[静電スプレー塗布中、ガン内チューブ・ノズル残インクが噴出し付着],ガン内残インクが噴出し付着,スプレーガン内のインク残り,0.85,"[{'text': '2・3ガン目の印加電圧を下げ、余剰ミストをアース板へ誘導', 'new...",2・3ガン目印加電圧低下でミスト低減(継続),レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': 'ベリファイ見落とし防止要領書で、左上から順に検査を指導', 'new'...",左上から順にベリファイ指導、感度設定変更,作業者への注意喚起,0.15,AVIベリファイ,AVIベリファイ,True,レジストインク付着（静電スプレー塗布由来）,不良品,客先責なし
29,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,[本報告書には記載がありません],本報告書には記載がありません,スプレーガン内のインク残り,0.0,"[{'text': '対策なし', 'new': True, 'reason': '本故障モ...",対策なし,レジスト塗布時の印加電圧を変更,0.05,...,"[{'text': '左上から順に検査するよう指導', 'new': True, 'reas...",左上から順に検査指導、感度設定変更,作業者への注意喚起,0.2,AVIベリファイ,AVIベリファイ,True,AVI検査ベリファイ誤判定による流出,不良品,客先責なし
30,2237034,file://meias889/file/kosyou/2237/q2237034.pdf,[現像ラインのコンベアー接触でドライフィルム破れ],現像ライン接触でDF破れ銅箔残り,ドライフィルム破れ,0.85,"[{'text': '水洗ラインのフィルター交換後、DF片付着無を確認', 'new': F...",対策なし(継続),コンベア間の速度調整,0.0,...,"[{'text': '出荷検査へ形状FBし、スリット部銅箔残り確認を徹底', 'new': ...",出荷検査へ形状FB・要領書追記,作業者への注意喚起,0.35,出荷,出荷,True,銅箔残り(金型先穴部),不良品,客先責なし
31,2237176,file://meias889/file/kosyou/2237/q2237176.pdf,[露光工程のフィルムセット時、耳が接触しピン・テープ外れで位置ずれ],露光時、フィルム耳接触で位置ずれ,露光フィルムのずれ,0.9,"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",フィルム耳を10mm以下へ変更,露光フィルムの固定用のテープ貼り付け位置の変更,0.4,...,"[{'text': '出荷検査工程に形状写真を回覧', 'new': True, 'reas...",4隅後に狭隙部追加確認、写真回覧,作業者への注意喚起,0.25,出荷,最終外観目視,False,レジストずれ,不良品,客先責なし
32,2237177,file://meias889/file/kosyou/2237/q2237177.pdf,[スプレーガン内チューブ・ノズルに残インク蓄積し噴き出して付着],スプレーガン残インク噴き出し付着,スプレーガン内のインク残り,0.85,"[{'text': '2・3ガン目の印加電圧を下げミストをアース板へ誘導', 'new': ...",印加電圧低下でミスト付着軽減(継続),レジスト塗布時のON/OFF動作の変更検証,0.25,...,"[{'text': '目視検査員へ形状写真回覧しパッド不具合検出を指導', 'new': T...",目視検査でパッド不具合検出を指導,作業者への注意喚起,0.6,最終外観目視,AVIベリファイ,False,レジストインク付着（パッド上）,不良品,客先責なし
33,2237178,file://meias889/file/kosyou/2237/q2237178.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.75,"[{'text': '外層現像後水洗ラインのフィルター交換後、DF片付着有無を確認', 'n...",水洗フィルター確認、DFラミメンテ,なし,0.0,...,"[{'text': '中間検査工程へ欠損形状をフィードバックし流出を認識させた', 'new...",中間検査へ欠損形状をフィードバック,作業者への注意喚起,0.45,パターン目視,パターン目視,True,外層パターン欠損（パッド欠損）,不良品,客先責なし
34,2238138,file://meias889/file/kosyou/2238/q2238138.pdf,[露光機へ基板セット時、フィルム耳が板に接触しピン/テープ外れで位置ずれ],露光機セット時のフィルム耳接触で位置ずれ,露光フィルムのずれ,0.9,"[{'text': '露光フィルム耳部分を10mm以下へ変更', 'new': True, ...",露光フィルム耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.9,...,"[{'text': '出荷検査工程へ形状写真を回覧', 'new': True, 'reas...",形状写真回覧・狭隙部追加確認・製品カードコメント,BGA、QFP、SOPなどの狭ピッチ部の重点確認を要領書に追加,0.8,最終外観目視,最終外観目視【/出荷】,False,レジストずれ,不良品,客先責なし
35,2239135,file://meias889/file/kosyou/2239/q2239135.pdf,[露光機セット時にフィルム耳が板へ接触し、ピンとテープが外れて基板とフィルムがずれた],露光機セットでフィルムがずれた,露光フィルムのずれ,0.90,"[{'text': '露光フィルムの耳部分を10mm以下へ変更', 'new': True,...",露光フィルムの耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.92,...,"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",形状写真回覧、狭隙部も追加確認,レジストとパターンの間隙が50μmの場合、製品カードに「要注意品」との記載を追記,0.6,最終外観目視,最終外観目視,True,レジストずれ,不良品,客先責なし
36,223X008,file://meias889/file/kosyou/223X/q223X008.pdf,[回路露光時の基板表面への異物付着で回路形成不良],回路露光時の異物付着で短絡発生,異物による露光阻害,0.75,"[{'text': '回路工程責任者/作業者へ不具合写真回覧', 'new': True, ...",回路工程で不具合写真を回覧,なし,0.0,...,"[{'text': '検査員へ不具合写真/現品回覧し周知', 'new': True, 'r...",検査員へ写真/現品回覧し再教育,作業者への注意喚起,0.35,AVIベリファイ,AVIベリファイ,True,パッド短絡,不良品,客先責なし
37,223X055,file://meias889/file/kosyou/223X/q223X055.pdf,[回路露光時、基板表面の異物付着で回路形成不良],回路露光時の異物付着で回路形成不良,異物による露光阻害,0.92,"[{'text': '回路工程へ不具合写真回覧し周知徹底', 'new': True, 'r...",回路工程へ不具合写真回覧し周知徹底,なし,0.0,...,"[{'text': '出荷検査員へ不具合写真と現品回覧', 'new': True, 're...",検査中断ルール教育、1シート完了徹底,作業者への注意喚起,0.4,AVIベリファイ,AVIベリファイ,True,パッド間の短絡（回路露光時の異物付着による回路形成不良／AVIベリファイで見落とし流出）,不良品,客先責なし
38,223X185,file://meias889/file/kosyou/223X/q223X185.pdf,[露光工程のフィルム耳が板に接触しピン・テープ外れ、基板とフィルムがずれた],露光時にフィルムが板接触し外れてずれ,露光フィルムのずれ,0.9,"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",露光用フィルム耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.95,...,"[{'text': '出荷検査工程へ形状写真回覧し認識徹底', 'new': True, '...",出荷検査へ形状写真回覧し認識徹底,レジストとパターンの間隙が50μmの場合、製品カードに「要注意品」との記載を追記,0.35,出荷,最終外観目視【/出荷】,False,レジストずれ,不良品,客先責なし
39,223X215,file://meias889/file/kosyou/223X/q223X215.pdf,"[レジスト露光時、インク片で露光フィルム浮き上がり露光阻害, スプレーガン内にインクが溜まり...",露光時インク片で露光阻害しレジスト残り,異物による露光阻害,0.9,"[{'text': '2・3ガン目印加電圧を下げ電位差で余分インクをアース板へ誘導', 'n...",2・3ガン目印加電圧低下でミスト低減(継続),なし,0.0,...,"[{'text': '目視検査員へ形状写真回覧し、パッド上不具合検出を重点指導', 'new...",目視検査員へ形状写真回覧し重点検査,作業者への注意喚起,0.35,AVIベリファイ,最終外観目視,False,レジストインク付着(露光不良)によるパッド欠損,不良品,客先責なし
40,223Y180,file://meias889/file/kosyou/223Y/q223Y180.pdf,[レジスト塗布前の基板セット時、投入機凸部へ接触しパターン変形],レジスト前処理研磨投入時の接触で回路曲がり,ハンドリング時の傷,0.6,"[{'text': '投入機突起を埋めるようボード設置し接触防止', 'new': True...",投入機突起対策＋接触時は中間検査再検査,研磨機の突起部をボードで覆う,0.6,...,"[{'text': '出荷検査工程に形状写真を回覧し流出を認識させた', 'new': Tr...",形状写真回覧し出荷・目視検査を重点化,作業者への注意喚起,0.45,出荷,AVI,False,ショート(パターン変形),不良品,客先責なし
41,2258070,file://meias889/file/kosyou/2258/q2258070.pdf,"[ルーター外形加工時、切削粉排出不良でスリット部に付着残留, 外形加工後の歯ブラシ除去で切削...",外形加工で切削粉排出不良となり残留,加工後のブラシ清掃不足,0.65,"[{'text': 'ルータービットを切削粉の排出性が良いものに変更', 'new': Tr...",排出性の良いルータービットへ変更(良品判定),ルータービット変更（排出性良いビット）,0.95,...,"[{'text': '出荷検査工程に形状回覧し流出を認識させた', 'new': True,...",出荷検査で形状回覧＋次回スリット粉検査(良品判定),注意喚起のみ？,0.25,出荷,出荷,True,切削粉残り,良品,客先責なし
42,2258088,file://meias889/file/kosyou/2258/q2258088.pdf,[レジスト塗布設備内にミストが付着し塊化、落下して製品へ付着],設備内付着ミストが塊化し落下、製品へ付着,余剰レジストインクが基板上に落下、付着,0.75,"[{'text': 'セミキュア後ロボット清掃、クリップ掴みシリンダー部にカバー設置', '...",ロボット清掃、カバー設置等で付着防止(継続),基板把持機構にセミキュア後にインク除去装置を追加,0.65,...,"[{'text': '出荷検査工程に形状を回覧し、今回形状の流出を認識させた', 'new'...",形状回覧と要領書でベリファイ誤判定防止,検査員の注意喚起のみ,0.50,AVIベリファイ,AVIベリファイ,True,レジストインク付着（パッドへの付着）,不良品,客先責なし
43,2258125,file://meias889/file/kosyou/2258/q2258125.pdf,[保護シール堆積インクが脱落・浮遊し基板へ付着],保護シール堆積インクが脱落し基板付着,余剰レジストインクが基板上に落下、付着,0.82,"[{'text': '上部以外の保護シール交換頻度を見直し', 'new': True, '...",保護シール交換頻度見直し・交換前清掃,スプレー側面/下面/ガンの保護シール交換頻度UP（1回/2W）上面の保護シールは交換頻度UP...,0.75,...,"[{'text': 'シルク下異物は現品確認を検討', 'new': False, 'rea...",対策なし,新規対策なし,0.8,AVIベリファイ,AVI【AVIベリファイでもよい？】,False,単一不良案件,不良品,客先責なし
44,2258135,file://meias889/file/kosyou/2258/q2258135.pdf,[不明],不明,発生要因不明。\n異物分析したが、シンボルインクと不一致。特定できず。,0.90,"[{'text': '対策なし', 'new': True, 'reason': '報告書の...",対策なし(客先責の疑い有),検査後～アルミ梱包作業を要点教育,0.05,...,"[{'text': '外観検査後～アルミ梱包まで清掃', 'new': True, 'rea...",外観検査後～梱包間の清掃・指導(客先責の疑い有),-,0.0,出荷,AVI【出荷】,False,単一不良案件,不良品,客先責の疑い有
45,2259008,file://meias889/file/kosyou/2259/q2259008.pdf,[OSP処理以降に外力で銅表面が削れキズ・レジスト剥がれ発生],OSP処理以降の外力で銅削れ・剥がれ,発生要因なし\nAVI検査～梱包出荷の現場調査したが、不具合要因なし,0.1,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(客先責の疑い有),-,0.1,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(客先責の疑い有),-,0.0,不明,AVI,False,キズ・レジスト剥がれ（外力による直線状キズ／銅露出）,不良品,客先責の疑い有
46,2259032,file://meias889/file/kosyou/2259/q2259032.pdf,[ノズル仕切り板の劣化でインク堆積・垂れ付着],ノズル仕切り板劣化でインク堆積・垂れ付着,ノズル変形によるインク堆積、滴下\nノズルメンテナンスはメーカ対応,0.85,"[{'text': '工程基準にノズル定期メンテ追加(1回/15日)', 'new': Tr...",ノズル定期メンテ(1回/15日)追加(良品判定),Kingwongでのノズル清掃・点検の定期化（1回/15日）,0.88,...,"[{'text': 'パッド付近インク飛散を不良化し教育', 'new': True, 'r...",パッド周辺飛散を不良化し検査員教育(良品判定),不良基準改定,0.8,AVIベリファイ,AVIベリファイ,True,IC9E 11ﾋﾟﾝ付近のシルクインク付着（シルク飛散）,良品,客先責なし
47,2259049,file://meias889/file/kosyou/2259/q2259049.pdf,[スプレーラインブース保護シールのインク堆積が脱落し基板へ付着],保護シール堆積インクが脱落し付着,余剰レジストインクが基板上に落下、付着,0.8,"[{'text': '上部以外も保護シール交換頻度を見直し', 'new': True, '...",側面等もシール交換頻度見直し・清掃標準化,スプレー側面/下面/ガンの保護シール交換頻度UP（1回/2W）上面の保護シールは交換頻度UP...,0.85,...,"[{'text': '受け入れ検査で検出時にKINWONGへフィードバック', 'new':...",受け入れ検査で検出時に客先へFB,新規対策なし,0.1,AVI,AVI,True,レジスト異物の上にマーキングされている,不良品,客先責なし
48,2259121,file://meias889/file/kosyou/2259/q2259121.pdf,[出荷検査工程のレジスト修正作業でレジストインク片が付着],出荷検査工程の修正作業でインク片付着,①修正作業時のインク付着\n②塗布ムラ,0.8,"[{'text': '出荷検査工程で写真回覧し検査員に周知', 'new': True, '...",写真回覧し注意事項を再指導(良品判定),対策の提示なし,0.1,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.90,不明,①再出荷検査\n②AVI,False,レジスト異物（マーキング上の緑色異物付着）,良品,客先責なし
49,2259121,file://meias889/file/kosyou/2259/q2259121.pdf,[真空引き時のしごきローラーで厚いレジストが押し広げられムラ化],真空引きでレジスト厚部が拡大しムラ,①修正作業時のインク付着\n②塗布ムラ,0.7,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.85,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.85,不明,①再出荷検査\n②AVI,False,レジストムラ（レジスト露光時の外観ムラ）,良品,客先責なし

NameError: name 'comare' is not defined

In [10]:
display(df_joined[cols])
df_joined[cols].to_excel('out_joined.xlsx', index=False)

,report_no,pdf_file,occurrence_cause,occurrence_cause_output,発生要因,発生要因比較,corrective_actions,corrective_actions_output,発生対策,発生対策比較,...,escape_countermeasures,escape_countermeasures_output,流出対策,流出対策比較,inspection_process,検査工程,検査工程比較,failure_mode,good_judgement,customer_responsibility
0,2215010,file://meias889/file/kosyou/2215/q2215010.pdf,[積層セットアップ時に真鍮製異物がL4回路へ混入],積層セットアップ時に真鍮製異物がL4混入,ハトメピンの破片の混入,0.7,"[{'text': 'ハトメ機周辺に粘着シート設置し異物監視', 'new': True, ...",粘着シート監視・清掃指導徹底,粘着シートを設置し、破片の発生個所の確認,0.75,...,"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",対策なし,なし,0.9,電気,電気,True,真鍮製異物混入によるL4層ショート,不良品,客先責なし
1,2215169,file://meias889/file/kosyou/2215/q2215169.pdf,[回路露光時の基板表面への異物付着で未露光となったため],回路露光時の異物付着で未露光となった,異物による露光阻害,0.95,"[{'text': '回路工程作業者へ不具合写真回覧で認識徹底', 'new': True,...",ED入室前ローラ清掃ルール化、不具合写真回覧,EDライン入室時はクリーン服を粘着ローラで清掃,0.9,...,"[{'text': '出荷検査員へ現品・写真確認を指示し認識徹底', 'new': True...",外観検査機設定強化、検査員へ現品写真確認,作業者への注意喚起,0.35,AVI,AVI,True,単一不良案件,不良品,客先責なし
2,2216105,file://meias889/file/kosyou/2216/q2216105.pdf,"[版と製品ずれでインクがクリアランスに入り込みにじみ発生, 試し刷りでずれを見逃し、そのまま...",版と製品ずれでインクが溜まりにじみ,印刷版裏へのインクにじみ,0.60,"[{'text': '試し刷りでクリアランスに掛かる場合は微調整', 'new': True...",試し刷り微調整・50μmマージン確保,版の位置の微調整を作業要領書で再規定・教育,0.6,...,"[{'text': '出荷検査工程へ通知し検査員へ周知徹底', 'new': True, '...",検査員へ周知し外形加工前AVI検査,作業者への注意喚起,0.35,出荷,AVIベリファイ【最終外観目視】,False,マーキングにじみ（マーキング罫線がにじみ、パッド上に乗り上げ）,不良品,客先責なし
3,2219198,file://meias889/file/kosyou/2219/q2219198.pdf,"[版と製品のずれ(約70～130μm)とにじみで乗り上げ, インクがパッド・レジスト間に入り...",版ずれと新品インク起因のにじみで乗り上げ,印刷版裏へのインクにじみ,0.6,"[{'text': '微調整でレジスト境界から50μm以上確保', 'new': False...",微調整再指導と新品インク時のW確認、版変更,版のメッシュ開口を微細化,0.5,...,"[{'text': '出荷検査へ形状FBし誤判定流出を周知(10/1)', 'new': T...",虚報多発時はロット識別し重点検査依頼書発行,検査画面の区分線追加による強調表示,0.15,AVIベリファイ,AVIベリファイ,True,マーキングにじみによるパッドへの乗り上げ,不良品,客先責なし
4,2223007,file://meias889/file/kosyou/2223/q2223007.pdf,[レジスト再生処理の水洗後、剥離作業手袋で扱い汚れ付着],水洗後、剥離作業手袋で扱い汚れ付着,レジスト再処理時の手袋からの転写,0.90,"[{'text': '剥離液出し入れ用ゴム手袋で他作業しない指導', 'new': True...",手袋の他作業禁止を指導・要領書明記,再処理工程の手袋の使用規定の再教育,0.75,...,"[{'text': '銅変色検出時の処置を整理し要領書で明確化・周知', 'new': Tr...",銅変色検出時の処置を要領書明確化,パッド上の変色への対応を明文化,0.95,AVIベリファイ,AVIベリファイ,True,半田濡れ不良（レジスト残渣付着）,不良品,客先責なし
5,2224076,file://meias889/file/kosyou/2224/q2224076.pdf,[バケット運搬時の重ね積み・擦れで印刷文字が剥離],バケット運搬時の重ね積み・擦れで剥離,搬送箱内での振動による基板同士の擦れ,0.85,"[{'text': 'バケット運搬時注意点を作業者全員に指導', 'new': True, ...",バケット運搬注意点を全員指導,作業者への注意喚起,0.75,...,"[{'text': '出荷検査へ形状FBし検出力向上', 'new': True, 'rea...",出荷検査へ形状FBし検出力向上,作業者への注意喚起,0.15,出荷,出荷,True,マーキング文字欠け,不良品,客先責なし
6,2228030,file://meias889/file/kosyou/2228/q2228030.pdf,"[集塵吸引で基板浮き、固定テープ剥がれ, 基板がガイドピンから外れ位置ずれ, ずれた状態で下...",集塵吸引でテープ剥がれ、基板ずれ下穴加工,ルーター加工時の固定テープの剥がれ,0.75,"[{'text': '不具合内容説明と現品回覧で作業者に認識', 'new': True, ...",テープ剥がれ時の異常処置明確化と上長連絡徹底,テープ剥がれ時の異常処置を明文化,0.85,...,"[{'text': '出荷検査員へ不具合説明し現品/写真回覧で教育', 'new': Tru...",出荷検査教育と外観検査機対応品へ登録,作業者への注意喚起,0.15,出荷,出荷,True,不要穴（φ1.5、5穴）発生（外形ルーター加工時の下穴ドリル加工ずれ）,不良品,客先責なし
7,2229127,file://meias889/file/kosyou/2229/q2229127.pdf,[スプレーガン真鍮チューブ内の残インクが噴き出し付着],真鍮チューブ内残インク噴き出し付着,スプレーガン内のインク残り,0.65,"[{'text': 'スプレーガン内真鍮チューブを取り外し清掃', 'new': True,...",真鍮チューブ清掃と月1回交換運用,スプレーガンの真鍮チューブの清掃頻度を1年/回→1月/回に変更,0.8,...,"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",形状写真回覧、次回検査前確認、週次共有,作業者への注意喚起,0.6,出荷,最終外観目視【/出荷】,False,レジストインク付着によるレジスト剥がれ,不良品,客先責なし
8,222X093,file://meias889/file/kosyou/222X/q222X093.pdf,[外層現像ラインで異物付着しめっき析出阻害→エッチングで欠損],外層現像ライン異物付着で欠損,異物による露光阻害,0.75,"[{'text': '外層現像前コンベアー速度調整・点検実施', 'new': True, ...",外層現像前コンベアー速度調整・点検,コンベア間の速度調整,0.7,...,"[{'text': '中間検査工程へクレーム発生通知書発行', 'new': True, '...",中間検査で履歴確認＋AOI適用,作業者への注意喚起,0.2,パターン目視,パターン目視,True,パッド欠損（回路形成時のエッチングによるパッド欠損）,不良品,客先責なし
9,222X122,file://meias889/file/kosyou/222X/q222X122.pdf,[レジスト露光時、フィルム固定ピンとテープが外れた状態で露光],露光時にピン・テープ外れでずれ,露光フィルムのずれ,0.9,"[{'text': 'ガイドピン外れ防止でテープ位置変更', 'new': True, 'r...",ピン外れ防止でテープ位置変更,露光フィルムの固定用のテープ貼り付け位置の変更,0.7,...,"[{'text': 'S面ずれ確認をランド→パッドへ変更し標準書改訂', 'new': Tr...",ずれ確認をパッドで実施し標準書改訂,ずれの確認箇所をランドからパッドに変更,0.9,最終外観目視,最終外観目視,True,レジストずれ,不良品,客先責なし
10,222X211,file://meias889/file/kosyou/222X/q222X211.pdf,[現像ラインの接触で穴上ドライフィルム破れ],現像ライン接触で穴上DF破れ,ドライフィルム破れ,0.90,"[{'text': '外層現像ラインを再度設備点検実施', 'new': True, 're...",外層現像ライン設備を再点検,コンベア間の速度調整,0.1,...,"[{'text': '中間検査・出荷検査へクレーム発生通知書発行', 'new': True...",クレーム通知・履歴書確認で検出力向上,作業者への注意喚起,0.15,出荷,出荷,True,きり穴銅箔残り,不良品,客先責なし
11,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,[回路露光機セット時の片手持ちでテープ剥離し、露光用フィルムがズレた],露光機セット時片手持ちでテープ剥離し、フィルムズレ発生,露光フィルムのずれ,0.9,"[{'text': '回路工程作業者へ不具合現品・写真を回覧し認識徹底', 'new': T...",露光機セット時は基板両端を持つよう教育徹底,基板の両手持ちの再教育,0.9,...,"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",パッド部は10倍ミニマスタ－確認をルール化,作業者への注意喚起,0.35,AVIベリファイ,AVIベリファイ,True,パタ－ンずれ（回路露光用フィルムズレ）によるパッド上レジスト被さり,不良品,客先責なし
12,222Y142,file://meias889/file/kosyou/222Y/q222Y142.pdf,[不明],不明,露光フィルムのずれ,0.0,"[{'text': '対策なし', 'new': True, 'reason': '本モード...",対策なし,基板の両手持ちの再教育,0.1,...,"[{'text': '出荷検査員へ不具合現品・写真回覧し流出を周知', 'new': Tru...",パッド部は10倍ミニマスタ－確認をルール化,作業者への注意喚起,0.5,AVIベリファイ,AVIベリファイ,True,出荷検査（外観検査機ベリファイ）での誤判定／見落としによる流出,不良品,客先責なし
13,222Z007,file://meias889/file/kosyou/222Z/q222Z007.pdf,[中間検査のショート修正で発生した銅片が回路間に残留],中間検査のショート修正で銅片残留,パターン修正時の銅片の再付着,0.88,"[{'text': '青テープを修正箇所1か所毎に交換し銅片除去', 'new': True...",青テープを修正1か所毎に交換し銅片除去,銅片除去に使用するテープの交換頻度を10回毎→1回毎に変更,0.95,...,"[{'text': '対策なし', 'new': True, 'reason': '報告書「...",対策なし,なし,0.85,電気,電気,True,内層ショート（銅片による回路間ショート）,不良品,客先責なし
14,222Z028,file://meias889/file/kosyou/222Z/q222Z028.pdf,[レジスト前処理機投入時、突起接触で当てキズ発生],レジスト投入機突起接触で当てキズ,ハンドリング時の傷,0.9,"[{'text': '投入機突起箇所にクッション取付', 'new': True, 'rea...",投入機突起へクッション取付・教育,投入機の角部にクッションを設置,0.75,...,"[{'text': '外観検査機で検出不可能なため、発生対策で再発防止', 'new': T...",検出不可のため発生対策で再発防止,なし,0.0,AVI,AVI,True,パタ－ン断線,不良品,客先責なし
15,222Z184,file://meias889/file/kosyou/222Z/q222Z184.pdf,[外観検査後、専用コンテナ投入時に基板角が他基板表面へ接触し擦れ発生],コンテナ投入時に基板角が接触し擦れ,ハンドリング時の傷,0.8,"[{'text': '専用コンテナへは25シート以内で基板をしっかり持ち、角の接触を防止',...",25シート以内で保持し接触防止(客先責の疑い有),作業者への注意喚起,0.15,...,[{'text': '専用コンテナ内の空きスペースにクッション材をセットし基板のズレを防止'...,空きスペースへクッション材設置(客先責の疑い有),なし,0.0,出荷,出荷,True,出荷検査完了以降の取り扱い接触によるパッド曲がり（パッド斜めずれ）,不良品,客先責の疑い有
16,2232028,file://meias889/file/kosyou/2232/q2232028.pdf,[スプレーガン内のチューブ・ノズル先にインク残り噴き出し付着],ガン内残インクが噴き出し付着,スプレーガン内のインク残り,0.9,"[{'text': 'スプレーガン内の真鍮製チューブを取外し清掃', 'new': Fals...",真鍮チューブ清掃・月1交換(継続),スプレーガンの真鍮チューブの清掃頻度を1年/回→1月/回に変更,0.92,...,"[{'text': '検査員へ形状写真回覧しパッド上不具合重点検査', 'new': Fal...",形状回覧し重点検査、検査員分離(継続),1ワーク当たりの検査時間を守れるように、検査員を分ける,0.7,AVI,最終外観目視,False,パッドへのレジストインク付着,不良品,客先責なし
17,2232052,file://meias889/file/kosyou/2232/q2232052.pdf,[ドライフィルムへ異物付着し浮き、めっき液潜り込みショート],ドライフィルム異物付着で浮き、めっき液潜り込みショート,異物によるめっきレジスト形成阻害,0.88,"[{'text': '端面切断をルータービット工法に統一', 'new': False, '...",クリーンローラー粘着シート交換を2回/日に,なし,0.0,...,"[{'text': '中間検査へフィードバックし目視注意点を指導', 'new': True...",ベリファイ手順見直し・全員周知で見落とし防止,作業者への注意喚起,0.6,AVIベリファイ,AVIベリファイ,True,外層ショート（IC48ピン－IC49ピン パッド間ショート）,不良品,客先責なし
18,2232121,file://meias889/file/kosyou/2232/q2232121.pdf,[スプレーガン内のインク残留が噴き出し付着],スプレーガン内インク残留が噴出し付着,スプレーガン内のインク残り,0.80,"[{'text': 'スプレーガン印加電圧を下げ付着軽減', 'new': True, 'r...",スプレーガン印加電圧低下で付着軽減,レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': '目視検査員へ形状写真回覧し重点検査', 'new': True, 'r...",目視重点化、検査員分離、時間設定,製品仕様毎に標準検査時間を設定,0.8,AVIベリファイ,最終外観目視,False,レジストインク付着（パッド上）,不良品,客先責なし
19,2233016,file://meias889/file/kosyou/2233/q2233016.pdf,[スプレーガン内に残ったインクが溜まり噴き出して付着],スプレーガン内残インクが噴き出し付着,スプレーガン内のインク残り,0.85,"[{'text': 'スプレーガンの印加電圧を下げ付着を軽減', 'new': True, ...",スプレーガン印加電圧を下げ付着軽減,レジスト塗布時の印加電圧を変更,0.85,...,"[{'text': '形状写真を回覧しパッド上不具合を重点検査', 'new': True,...",パッド上不具合を重点に目視検査強化,製品仕様毎に標準検査時間を設定,0.35,AVIベリファイ,最終外観目視,False,レジストインク付着,不良品,客先責なし
20,2233083,file://meias889/file/kosyou/2233/q2233083.pdf,"[シルク印刷前に塗装された木片が基板へ付着し残留, 梱包作業台の化粧合板側面破損で木片脱落・...",梱包作業台破損で木片脱落し付着,印刷時の異物混入,0.6,"[{'text': 'レジスト現像後・シルク印刷前の基板確認を周知徹底', 'new': T...",梱包作業台に金属カバー取付・周知,なし,0.0,...,"[{'text': '目視検査で異物付着検出を重点化し指導', 'new': True, '...",目視検査で異物付着を重点確認,作業者への注意喚起,0.30,AVI,最終外観目視,False,異物付着（塗装された木片の付着）,不良品,客先責なし
21,2234007,file://meias889/file/kosyou/2234/q2234007.pdf,[スプレーガン内チューブ・ノズル先に残ったインクが噴き出し付着],ガン内残留インクが噴出し付着,スプレーガン内のインク残り,0.8,"[{'text': '2・3ガン目の印加電圧を下げ電位差を作りミストをアース板へ誘導', '...",2・3ガン目電圧下げミスト誘導(継続),レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': '目視検査全員に形状写真回覧しパッド上不具合検出を重点指導', 'new...",形状写真回覧しパッド不具合重点検査,製品仕様毎に標準検査時間を設定,0.25,最終外観目視,最終外観目視,True,レジストインク付着,不良品,客先責なし
22,2234008,file://meias889/file/kosyou/2234/q2234008.pdf,"[端面研磨で外周銅の除去不十分により銅残り発生, レジスト塗布時に端面銅が脱落し銅屑が付着]",端面研磨不良で銅残り→銅屑が付着,端面研磨不足による端部への銅残り,0.95,"[{'text': '端面研磨機に注意事項掲示し銅残り防止', 'new': True, '...",端面銅残り厳禁掲示と25パネル毎確認,なし,0.0,...,"[{'text': '流出対策は発生対策で防止する', 'new': True, 'reas...",検出困難なため発生対策で流出防止,端面研磨後、25パネル毎に銅残りないことを確認する検査を追加,0.15,AVI,その他【AVI】,False,単一不良案件,不良品,客先責なし
23,2234164,file://meias889/file/kosyou/2234/q2234164.pdf,[マーキング印刷後～乾燥前に作業者毛髪が落下し付着],印刷後～乾燥前に毛髪落下し付着,印刷後の異物混入,0.85,"[{'text': '印刷作業時の服装を再指導（帽子耳まで）', 'new': True, ...",印刷作業時の帽子着用を再指導・表示,服装規定の追加掲示,0.7,...,"[{'text': '目視検査全員へ現品回覧し指導', 'new': True, 'reas...",ベリファイ全体確認・要領書追加等,見落としやすい不良項目として、教育資料に本不良写真を追加,0.65,AVIベリファイ,AVIベリファイ,True,毛髪異物付着（マーキング印刷後〜乾燥前の落下）／AVIベリファイで見落とし流出,不良品,客先責なし
24,2236115,file://meias889/file/kosyou/2236/q2236115.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.7,"[{'text': '外層現像ライン設備を再点検', 'new': True, 'reaso...",外層現像ライン再点検と水洗フィルター確認,なし,0.0,...,"[{'text': '中間検査工程へ形状フィードバックし流出認識', 'new': True...",中間検査へ形状FBし流出認識徹底,作業者への注意喚起,0.45,パターン目視,パターン目視,True,外層パターン断線（異物付着によるめっき析出阻害→欠損・断線／中間検査見逃し・通電検査で検出不可）,不良品,客先責なし
25,2236116,file://meias889/file/kosyou/2236/q2236116.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.35,"[{'text': '外層現像ラインのコンベアを点検', 'new': True, 'rea...",外層現像ライン点検、フィルター交換後確認,なし,0.0,...,"[{'text': '中間検査工程へ形状フィードバック実施', 'new': True, '...",中間検査へ形状フィードバック実施,作業者への注意喚起,0.2,パターン目視,パターン目視,True,外層パターン断線,不良品,客先責なし
26,2236121,file://meias889/file/kosyou/2236/q2236121.pdf,[端面研磨で外周銅が残り、レジスト工程で銅屑が脱落付着],端面研磨で外周銅が残り、銅屑が脱落付着,端面研磨不足による端部への銅残り,0.90,"[{'text': '端面研磨機に注意喚起掲示し銅残り防止', 'new': True, '...",端面銅残り厳禁掲示と25パネル毎確認,なし,0.0,...,"[{'text': '不具合現品回覧し見落としを情報展開', 'new': True, 'r...",ベリファイ教育と中断時の完了周知・要領書追記,検査中は中断禁止を要領書に追記,0.55,AVIベリファイ,AVIベリファイ,True,銅屑付着によるショ－ト,不良品,客先責なし
27,2236199,file://meias889/file/kosyou/2236/q2236199.pdf,[該当箇所のレジスト異物をカッターで削り取りした],レジスト異物をカッターで削り取り,レジスト修正時の塗布量が少ない,0.2,"[{'text': 'レジストインクを均一に塗布するよう修正時注意事項を再指導', 'new...",修正時、レジストインクを均一塗布へ再指導,塗布見本を要領書に追記,0.6,...,"[{'text': '今回の形状を出荷検査工程にフィードバック', 'new': True,...",今回の形状を出荷検査工程へフィードバック,作業者への注意喚起,0.25,出荷,その他【出荷】,False,レジスト不良(修正痕)（レジスト異物を削り取り、レジストインクを筆で塗布した修正品の出来栄え不良）,不良品,客先責なし
28,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,[静電スプレー塗布中、ガン内チューブ・ノズル残インクが噴出し付着],ガン内残インクが噴出し付着,スプレーガン内のインク残り,0.85,"[{'text': '2・3ガン目の印加電圧を下げ、余剰ミストをアース板へ誘導', 'new...",2・3ガン目印加電圧低下でミスト低減(継続),レジスト塗布時の印加電圧を変更,0.75,...,"[{'text': 'ベリファイ見落とし防止要領書で、左上から順に検査を指導', 'new'...",左上から順にベリファイ指導、感度設定変更,作業者への注意喚起,0.15,AVIベリファイ,AVIベリファイ,True,レジストインク付着（静電スプレー塗布由来）,不良品,客先責なし
29,2236200,file://meias889/file/kosyou/2236/q2236200.pdf,[本報告書には記載がありません],本報告書には記載がありません,スプレーガン内のインク残り,0.0,"[{'text': '対策なし', 'new': True, 'reason': '本故障モ...",対策なし,レジスト塗布時の印加電圧を変更,0.05,...,"[{'text': '左上から順に検査するよう指導', 'new': True, 'reas...",左上から順に検査指導、感度設定変更,作業者への注意喚起,0.2,AVIベリファイ,AVIベリファイ,True,AVI検査ベリファイ誤判定による流出,不良品,客先責なし
30,2237034,file://meias889/file/kosyou/2237/q2237034.pdf,[現像ラインのコンベアー接触でドライフィルム破れ],現像ライン接触でDF破れ銅箔残り,ドライフィルム破れ,0.85,"[{'text': '水洗ラインのフィルター交換後、DF片付着無を確認', 'new': F...",対策なし(継続),コンベア間の速度調整,0.0,...,"[{'text': '出荷検査へ形状FBし、スリット部銅箔残り確認を徹底', 'new': ...",出荷検査へ形状FB・要領書追記,作業者への注意喚起,0.35,出荷,出荷,True,銅箔残り(金型先穴部),不良品,客先責なし
31,2237176,file://meias889/file/kosyou/2237/q2237176.pdf,[露光工程のフィルムセット時、耳が接触しピン・テープ外れで位置ずれ],露光時、フィルム耳接触で位置ずれ,露光フィルムのずれ,0.9,"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",フィルム耳を10mm以下へ変更,露光フィルムの固定用のテープ貼り付け位置の変更,0.4,...,"[{'text': '出荷検査工程に形状写真を回覧', 'new': True, 'reas...",4隅後に狭隙部追加確認、写真回覧,作業者への注意喚起,0.25,出荷,最終外観目視,False,レジストずれ,不良品,客先責なし
32,2237177,file://meias889/file/kosyou/2237/q2237177.pdf,[スプレーガン内チューブ・ノズルに残インク蓄積し噴き出して付着],スプレーガン残インク噴き出し付着,スプレーガン内のインク残り,0.85,"[{'text': '2・3ガン目の印加電圧を下げミストをアース板へ誘導', 'new': ...",印加電圧低下でミスト付着軽減(継続),レジスト塗布時のON/OFF動作の変更検証,0.25,...,"[{'text': '目視検査員へ形状写真回覧しパッド不具合検出を指導', 'new': T...",目視検査でパッド不具合検出を指導,作業者への注意喚起,0.6,最終外観目視,AVIベリファイ,False,レジストインク付着（パッド上）,不良品,客先責なし
33,2237178,file://meias889/file/kosyou/2237/q2237178.pdf,[外層露光後～パターンめっき前の異物付着でめっき析出阻害],外層露光後～パターンめっき前の異物付着,異物による露光阻害,0.75,"[{'text': '外層現像後水洗ラインのフィルター交換後、DF片付着有無を確認', 'n...",水洗フィルター確認、DFラミメンテ,なし,0.0,...,"[{'text': '中間検査工程へ欠損形状をフィードバックし流出を認識させた', 'new...",中間検査へ欠損形状をフィードバック,作業者への注意喚起,0.45,パターン目視,パターン目視,True,外層パターン欠損（パッド欠損）,不良品,客先責なし
34,2238138,file://meias889/file/kosyou/2238/q2238138.pdf,[露光機へ基板セット時、フィルム耳が板に接触しピン/テープ外れで位置ずれ],露光機セット時のフィルム耳接触で位置ずれ,露光フィルムのずれ,0.9,"[{'text': '露光フィルム耳部分を10mm以下へ変更', 'new': True, ...",露光フィルム耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.9,...,"[{'text': '出荷検査工程へ形状写真を回覧', 'new': True, 'reas...",形状写真回覧・狭隙部追加確認・製品カードコメント,BGA、QFP、SOPなどの狭ピッチ部の重点確認を要領書に追加,0.8,最終外観目視,最終外観目視【/出荷】,False,レジストずれ,不良品,客先責なし
35,2239135,file://meias889/file/kosyou/2239/q2239135.pdf,[露光機セット時にフィルム耳が板へ接触し、ピンとテープが外れて基板とフィルムがずれた],露光機セットでフィルムがずれた,露光フィルムのずれ,0.90,"[{'text': '露光フィルムの耳部分を10mm以下へ変更', 'new': True,...",露光フィルムの耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.92,...,"[{'text': '出荷検査工程に形状写真を回覧し周知', 'new': True, 'r...",形状写真回覧、狭隙部も追加確認,レジストとパターンの間隙が50μmの場合、製品カードに「要注意品」との記載を追記,0.6,最終外観目視,最終外観目視,True,レジストずれ,不良品,客先責なし
36,223X008,file://meias889/file/kosyou/223X/q223X008.pdf,[回路露光時の基板表面への異物付着で回路形成不良],回路露光時の異物付着で短絡発生,異物による露光阻害,0.75,"[{'text': '回路工程責任者/作業者へ不具合写真回覧', 'new': True, ...",回路工程で不具合写真を回覧,なし,0.0,...,"[{'text': '検査員へ不具合写真/現品回覧し周知', 'new': True, 'r...",検査員へ写真/現品回覧し再教育,作業者への注意喚起,0.35,AVIベリファイ,AVIベリファイ,True,パッド短絡,不良品,客先責なし
37,223X055,file://meias889/file/kosyou/223X/q223X055.pdf,[回路露光時、基板表面の異物付着で回路形成不良],回路露光時の異物付着で回路形成不良,異物による露光阻害,0.92,"[{'text': '回路工程へ不具合写真回覧し周知徹底', 'new': True, 'r...",回路工程へ不具合写真回覧し周知徹底,なし,0.0,...,"[{'text': '出荷検査員へ不具合写真と現品回覧', 'new': True, 're...",検査中断ルール教育、1シート完了徹底,作業者への注意喚起,0.4,AVIベリファイ,AVIベリファイ,True,パッド間の短絡（回路露光時の異物付着による回路形成不良／AVIベリファイで見落とし流出）,不良品,客先責なし
38,223X185,file://meias889/file/kosyou/223X/q223X185.pdf,[露光工程のフィルム耳が板に接触しピン・テープ外れ、基板とフィルムがずれた],露光時にフィルムが板接触し外れてずれ,露光フィルムのずれ,0.9,"[{'text': '露光用フィルムの耳部分を10mm以下へ変更', 'new': True...",露光用フィルム耳を10mm以下へ変更,露光フィルムの耳部の長さを15→10mmに変更,0.95,...,"[{'text': '出荷検査工程へ形状写真回覧し認識徹底', 'new': True, '...",出荷検査へ形状写真回覧し認識徹底,レジストとパターンの間隙が50μmの場合、製品カードに「要注意品」との記載を追記,0.35,出荷,最終外観目視【/出荷】,False,レジストずれ,不良品,客先責なし
39,223X215,file://meias889/file/kosyou/223X/q223X215.pdf,"[レジスト露光時、インク片で露光フィルム浮き上がり露光阻害, スプレーガン内にインクが溜まり...",露光時インク片で露光阻害しレジスト残り,異物による露光阻害,0.9,"[{'text': '2・3ガン目印加電圧を下げ電位差で余分インクをアース板へ誘導', 'n...",2・3ガン目印加電圧低下でミスト低減(継続),なし,0.0,...,"[{'text': '目視検査員へ形状写真回覧し、パッド上不具合検出を重点指導', 'new...",目視検査員へ形状写真回覧し重点検査,作業者への注意喚起,0.35,AVIベリファイ,最終外観目視,False,レジストインク付着(露光不良)によるパッド欠損,不良品,客先責なし
40,223Y180,file://meias889/file/kosyou/223Y/q223Y180.pdf,[レジスト塗布前の基板セット時、投入機凸部へ接触しパターン変形],レジスト前処理研磨投入時の接触で回路曲がり,ハンドリング時の傷,0.6,"[{'text': '投入機突起を埋めるようボード設置し接触防止', 'new': True...",投入機突起対策＋接触時は中間検査再検査,研磨機の突起部をボードで覆う,0.6,...,"[{'text': '出荷検査工程に形状写真を回覧し流出を認識させた', 'new': Tr...",形状写真回覧し出荷・目視検査を重点化,作業者への注意喚起,0.45,出荷,AVI,False,ショート(パターン変形),不良品,客先責なし
41,2258070,file://meias889/file/kosyou/2258/q2258070.pdf,"[ルーター外形加工時、切削粉排出不良でスリット部に付着残留, 外形加工後の歯ブラシ除去で切削...",外形加工で切削粉排出不良となり残留,加工後のブラシ清掃不足,0.65,"[{'text': 'ルータービットを切削粉の排出性が良いものに変更', 'new': Tr...",排出性の良いルータービットへ変更(良品判定),ルータービット変更（排出性良いビット）,0.95,...,"[{'text': '出荷検査工程に形状回覧し流出を認識させた', 'new': True,...",出荷検査で形状回覧＋次回スリット粉検査(良品判定),注意喚起のみ？,0.25,出荷,出荷,True,切削粉残り,良品,客先責なし
42,2258088,file://meias889/file/kosyou/2258/q2258088.pdf,[レジスト塗布設備内にミストが付着し塊化、落下して製品へ付着],設備内付着ミストが塊化し落下、製品へ付着,余剰レジストインクが基板上に落下、付着,0.75,"[{'text': 'セミキュア後ロボット清掃、クリップ掴みシリンダー部にカバー設置', '...",ロボット清掃、カバー設置等で付着防止(継続),基板把持機構にセミキュア後にインク除去装置を追加,0.65,...,"[{'text': '出荷検査工程に形状を回覧し、今回形状の流出を認識させた', 'new'...",形状回覧と要領書でベリファイ誤判定防止,検査員の注意喚起のみ,0.50,AVIベリファイ,AVIベリファイ,True,レジストインク付着（パッドへの付着）,不良品,客先責なし
43,2258125,file://meias889/file/kosyou/2258/q2258125.pdf,[保護シール堆積インクが脱落・浮遊し基板へ付着],保護シール堆積インクが脱落し基板付着,余剰レジストインクが基板上に落下、付着,0.82,"[{'text': '上部以外の保護シール交換頻度を見直し', 'new': True, '...",保護シール交換頻度見直し・交換前清掃,スプレー側面/下面/ガンの保護シール交換頻度UP（1回/2W）上面の保護シールは交換頻度UP...,0.75,...,"[{'text': 'シルク下異物は現品確認を検討', 'new': False, 'rea...",対策なし,新規対策なし,0.8,AVIベリファイ,AVI【AVIベリファイでもよい？】,False,単一不良案件,不良品,客先責なし
44,2258135,file://meias889/file/kosyou/2258/q2258135.pdf,[不明],不明,発生要因不明。\n異物分析したが、シンボルインクと不一致。特定できず。,0.90,"[{'text': '対策なし', 'new': True, 'reason': '報告書の...",対策なし(客先責の疑い有),検査後～アルミ梱包作業を要点教育,0.05,...,"[{'text': '外観検査後～アルミ梱包まで清掃', 'new': True, 'rea...",外観検査後～梱包間の清掃・指導(客先責の疑い有),-,0.0,出荷,AVI【出荷】,False,単一不良案件,不良品,客先責の疑い有
45,2259008,file://meias889/file/kosyou/2259/q2259008.pdf,[OSP処理以降に外力で銅表面が削れキズ・レジスト剥がれ発生],OSP処理以降の外力で銅削れ・剥がれ,発生要因なし\nAVI検査～梱包出荷の現場調査したが、不具合要因なし,0.1,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(客先責の疑い有),-,0.1,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(客先責の疑い有),-,0.0,不明,AVI,False,キズ・レジスト剥がれ（外力による直線状キズ／銅露出）,不良品,客先責の疑い有
46,2259032,file://meias889/file/kosyou/2259/q2259032.pdf,[ノズル仕切り板の劣化でインク堆積・垂れ付着],ノズル仕切り板劣化でインク堆積・垂れ付着,ノズル変形によるインク堆積、滴下\nノズルメンテナンスはメーカ対応,0.85,"[{'text': '工程基準にノズル定期メンテ追加(1回/15日)', 'new': Tr...",ノズル定期メンテ(1回/15日)追加(良品判定),Kingwongでのノズル清掃・点検の定期化（1回/15日）,0.88,...,"[{'text': 'パッド付近インク飛散を不良化し教育', 'new': True, 'r...",パッド周辺飛散を不良化し検査員教育(良品判定),不良基準改定,0.8,AVIベリファイ,AVIベリファイ,True,IC9E 11ﾋﾟﾝ付近のシルクインク付着（シルク飛散）,良品,客先責なし
47,2259049,file://meias889/file/kosyou/2259/q2259049.pdf,[スプレーラインブース保護シールのインク堆積が脱落し基板へ付着],保護シール堆積インクが脱落し付着,余剰レジストインクが基板上に落下、付着,0.8,"[{'text': '上部以外も保護シール交換頻度を見直し', 'new': True, '...",側面等もシール交換頻度見直し・清掃標準化,スプレー側面/下面/ガンの保護シール交換頻度UP（1回/2W）上面の保護シールは交換頻度UP...,0.85,...,"[{'text': '受け入れ検査で検出時にKINWONGへフィードバック', 'new':...",受け入れ検査で検出時に客先へFB,新規対策なし,0.1,AVI,AVI,True,レジスト異物の上にマーキングされている,不良品,客先責なし
48,2259121,file://meias889/file/kosyou/2259/q2259121.pdf,[出荷検査工程のレジスト修正作業でレジストインク片が付着],出荷検査工程の修正作業でインク片付着,①修正作業時のインク付着\n②塗布ムラ,0.8,"[{'text': '出荷検査工程で写真回覧し検査員に周知', 'new': True, '...",写真回覧し注意事項を再指導(良品判定),対策の提示なし,0.1,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.90,不明,①再出荷検査\n②AVI,False,レジスト異物（マーキング上の緑色異物付着）,良品,客先責なし
49,2259121,file://meias889/file/kosyou/2259/q2259121.pdf,[真空引き時のしごきローラーで厚いレジストが押し広げられムラ化],真空引きでレジスト厚部が拡大しムラ,①修正作業時のインク付着\n②塗布ムラ,0.7,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.85,...,"[{'text': '対策なし', 'new': True, 'reason': '本報告書...",対策なし(良品判定),対策の提示なし,0.85,不明,①再出荷検査\n②AVI,False,レジストムラ（レジスト露光時の外観ムラ）,良品,客先責なし